export const APP_KEY = "the_obelisk_prototype_v1";
export const MAP_HEIGHT = 30;
export const ACT_LENGTH = 10;
export const ACT_COUNT = 3;
export const BASE_TIME_LIMIT = 8000;
export const ACT_TIME_LIMITS = [12000, 10000, BASE_TIME_LIMIT];
export const QUICK_WINDOW_MS = 3000;
export const BASE_ENERGY_PER_TURN = 3;
export const BASE_ULTIMATE_CHARGE_REQUIRED = 10;

export const NODE_TYPES = {
  MONSTER: "MONSTER",
  ELITE: "ELITE",
  EVENT: "EVENT",
  REST: "REST",
  TREASURE: "TREASURE",
  SHOP: "SHOP",
  BOSS: "BOSS",
};

export const NODE_ICONS = {
  MONSTER: "M",
  ELITE: "E",
  EVENT: "?",
  REST: "R",
  TREASURE: "T",
  SHOP: "S",
  BOSS: "B",
};

export const NODE_ASSETS = {
  MONSTER: "./assets/nodes/node-monster.png",
  ELITE: "./assets/nodes/node-elite.png",
  EVENT: "./assets/nodes/node-event.png",
  REST: "./assets/nodes/node-rest.png",
  TREASURE: "./assets/nodes/node-treasure.png",
  SHOP: "./assets/nodes/node-shop.png",
  BOSS: "./assets/nodes/node-boss.png",
};

export const LEGENDS = [
  {
    id: "knight",
    name: "Knight",
    icon: "K",
    asset: "./assets/legends/legend-knight-portrait.png",
    color: "legend-knight",
    description: "The Bulwark of the Frontier.",
    hp: 120,
    stats: { str: 10, vit: 12, focus: 5 },
    startingBlock: 20,
    passive: "Starts each battle with bonus barrier.",
    starterActions: {
      atk: {
        name: "Frontier Slash",
        detail: "A disciplined single-target cut that keeps the line under control.",
      },
      blk: {
        name: "Shield Ward",
        detail: "Raise your shield and turn a clean answer into sturdy barrier.",
      },
      aoe: {
        name: "Banner Sweep",
        detail: "Sweep the whole front and batter every foe with one hard strike.",
      },
    },
  },
  {
    id: "wizard",
    name: "Wizard",
    icon: "W",
    asset: "./assets/legends/legend-wizard-portrait.png",
    color: "legend-wizard",
    description: "Master of volatile equations.",
    hp: 80,
    stats: { str: 14, vit: 6, focus: 10 },
    startingBlock: 0,
    passive: "Quick HARD answers hit much harder.",
    starterActions: {
      atk: {
        name: "Arcane Bolt",
        detail: "Fire a clean bolt of force into one marked foe.",
      },
      blk: {
        name: "Prism Ward",
        detail: "Bend the answer into a quick ward of refracted force.",
      },
      aoe: {
        name: "Frost Nova",
        detail: "Flash-freeze the room with a hard cast that hits every foe.",
      },
    },
  },
  {
    id: "rogue",
    name: "Rogue",
    icon: "R",
    asset: "./assets/legends/legend-rogue-portrait.png",
    color: "legend-rogue",
    description: "Death by a thousand cuts.",
    hp: 100,
    stats: { str: 8, vit: 8, focus: 14 },
    startingBlock: 0,
    passive: "Combo and critical tempo stay online longer.",
    starterActions: {
      atk: {
        name: "Shiv",
        detail: "A quick knife strike that keeps your tempo sharp.",
      },
      blk: {
        name: "Shadow Slip",
        detail: "Slip through the gap and turn a clean answer into cover and breathing room.",
      },
      aoe: {
        name: "Blade Gust",
        detail: "Whip a spread of steel through the whole pack with one hard throw.",
      },
    },
  },
];

export const SPIRES = [
  {
    id: "addition",
    name: "Starfall Spire",
    symbol: "+",
    asset: "./assets/spires/spire-addition-emblem.png",
    description: "An addition-bound ascent where totals swell with each act.",
  },
  {
    id: "subtraction",
    name: "Ashen Hollow",
    symbol: "-",
    asset: "./assets/spires/spire-subtraction-emblem.png",
    description: "A subtraction-forged climb built on clean cuts and ruthless differences.",
  },
  {
    id: "multiplication",
    name: "Forge of Echoes",
    symbol: "*",
    asset: "./assets/spires/spire-multiplication-emblem.png",
    description: "A multiplication route of explosive scaling and high-risk burst math.",
  },
  {
    id: "division",
    name: "The Split Sanctum",
    symbol: "/",
    asset: "./assets/spires/spire-division-emblem.png",
    description: "A division-carved tower demanding precise reads and clean integer answers.",
  },
  {
    id: "mixed",
    name: "The Obelisk Crown",
    symbol: "MIX",
    asset: "./assets/spires/spire-mixed-emblem.png",
    description: "A crowned ascent whose lessons widen as the summit nears.",
  },
];

export const MATERIALS = {
  emberwood: {
    id: "emberwood",
    name: "Emberwood",
    short: "Emberwood",
    rarity: "UNCOMMON",
    description: "Smoldering timber cut from the frontier's oldest siege groves. The base uses it to frame gates, archives, and war tables.",
  },
  thorium: {
    id: "thorium",
    name: "Thorium",
    short: "Thorium",
    rarity: "RARE",
    description: "Dense runic metal pried from elite vaultworks. It stabilizes spire portals, forge rigs, and deep combat chambers.",
  },
  eternium: {
    id: "eternium",
    name: "Eternium",
    short: "Eternium",
    rarity: "LEGENDARY",
    description: "Mythic star-metal recovered from the hardest bosses. Every fragment can redefine what future runs are allowed to contain.",
  },
};

export const HERBS = {
  white: {
    id: "white",
    name: "White Herb",
    short: "White",
    rarity: "COMMON",
    description: "A pale field herb used in the weakest recovery brews.",
  },
  yellow: {
    id: "yellow",
    name: "Yellow Herb",
    short: "Yellow",
    rarity: "UNCOMMON",
    description: "A sun-cured stem used for stronger restorative tonics.",
  },
  red: {
    id: "red",
    name: "Red Herb",
    short: "Red",
    rarity: "RARE",
    description: "A fierce scarlet herb prized for deep healing brews.",
  },
  blue: {
    id: "blue",
    name: "Blue Herb",
    short: "Blue",
    rarity: "RARE",
    description: "A cold arcane sprig used in brews that restore energy.",
  },
};

export const POTIONS = {
  white: {
    id: "white",
    herbId: "white",
    name: "White Tonic",
    short: "W",
    kind: "HEAL",
    healPct: 0.14,
    description: "Restore 14% max HP.",
  },
  yellow: {
    id: "yellow",
    herbId: "yellow",
    name: "Yellow Tonic",
    short: "Y",
    kind: "HEAL",
    healPct: 0.21,
    description: "Restore 21% max HP.",
  },
  red: {
    id: "red",
    herbId: "red",
    name: "Red Tonic",
    short: "R",
    kind: "HEAL",
    healPct: 0.28,
    description: "Restore 28% max HP.",
  },
  blue: {
    id: "blue",
    herbId: "blue",
    name: "Blue Tonic",
    short: "B",
    kind: "ENERGY",
    energyRestore: 1,
    description: "Restore 1 energy in battle.",
  },
};

export const BASE_ACTIONS = [
  { id: "atk", name: "Strike", type: "ATK", value: 1.0, baseValue: 1.0, level: 1, energyCost: 1, color: "action-attack", difficulty: "EASY", hotkey: "A", detail: "Reliable single-target damage. Your simplest and safest attack." },
  { id: "blk", name: "Guard", type: "DEF", value: 1.2, baseValue: 1.2, level: 1, energyCost: 1, color: "action-guard", difficulty: "EASY", hotkey: "S", detail: "Gain barrier from a correct answer and blunt the next hit." },
  { id: "aoe", name: "Sunder Wave", type: "AOE", value: 0.7, baseValue: 0.7, level: 1, energyCost: 2, color: "action-aoe", difficulty: "HARD", hotkey: "D", detail: "Hard cast. Hits every foe and breaks clustered formations." },
  { id: "util", name: "Sealed Art", type: "UTILITY", value: 0, baseValue: 0, level: 1, energyCost: 2, color: "action-heal", difficulty: "HARD", hotkey: "F", detail: "Locked utility slot. Learn a restoration art to open it mid-run.", requiresUnlock: "utilitySlotUnlocked" },
];

export const ULTIMATES = {
  knight: {
    id: "ult-knight",
    name: "Guardian Bash",
    legendId: "knight",
    type: "ULTIMATE",
    difficulty: "HARD",
    hotkey: "G",
    color: "action-ultimate-knight",
    detail: "Crush one foe, stun it for a turn, and restore barrier to yourself.",
    tags: ["TARGET", "STUN", "BLOCK"],
    baseDamage: 1.45,
    blockGain: 18,
    stunTurns: 1,
  },
  wizard: {
    id: "ult-wizard",
    name: "Arcstorm Nova",
    legendId: "wizard",
    type: "ULTIMATE",
    difficulty: "HARD",
    hotkey: "G",
    color: "action-ultimate-wizard",
    detail: "Detonate a room-wide arcane blast that slams every enemy at once.",
    tags: ["AOE", "BURST"],
    baseDamage: 2.3,
  },
  rogue: {
    id: "ult-rogue",
    name: "Shadow Flurry",
    legendId: "rogue",
    type: "ULTIMATE",
    difficulty: "HARD",
    hotkey: "G",
    color: "action-ultimate-rogue",
    detail: "Unload a focused multi-slash finisher with a high crit chance.",
    tags: ["TARGET", "MULTI", "CRIT"],
    baseDamage: 0.72,
    hits: 3,
    bonusCritChance: 28,
  },
};

export const ACTION_EVOLUTIONS = {
  knight: [
    {
      id: "knight-shield-rush",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Shield Rush",
      unlockTitle: "Shield Rush",
      unlockDescription: "Reforge Strike into a shield charge that hurts one foe and raises barrier.",
      patch: {
        name: "Shield Rush",
        value: 0.9,
        detail: "Shield charge one foe, deal solid damage, and gain barrier.",
        blockGain: 12,
        animationKey: "shield-rush",
      },
    },
    {
      id: "knight-execution-drive",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Execution Drive",
      unlockTitle: "Execution Drive",
      unlockDescription: "Reforge Strike into a two-cut finisher for focused burst and sharper crits.",
      patch: {
        name: "Execution Drive",
        difficulty: "HARD",
        value: 0.78,
        hits: 2,
        bonusCritChance: 12,
        detail: "Land two precise cuts on one foe with elevated crit chance.",
        animationKey: "execution-drive",
      },
    },
    {
      id: "knight-bulwark-form",
      order: 2,
      tier: 2,
      actionId: "blk",
      name: "Bulwark Form",
      unlockTitle: "Bulwark Form",
      unlockDescription: "Reforge Guard into a heavier stance with stronger barrier and battlefield presence.",
      patch: {
        name: "Bulwark Form",
        value: 1.35,
        detail: "Raise heavier barrier and hold the line under pressure.",
        animationKey: "bulwark-form",
      },
    },
    {
      id: "knight-sanctuary-banner",
      order: 3,
      tier: 3,
      actionId: "util",
      name: "Sanctuary Banner",
      unlockTitle: "Sanctuary Banner",
      unlockDescription: "Open the sealed utility slot with a banner that restores health and fortifies the line.",
      patch: {
        name: "Sanctuary Banner",
        energyCost: 2,
        flatHeal: 14,
        healPct: 0.08,
        blockGain: 12,
        detail: "Raise a warding banner to heal yourself and gain barrier.",
        animationKey: "sanctuary-banner",
      },
    },
    {
      id: "knight-marshals-oath",
      order: 3,
      tier: 3,
      actionId: "util",
      name: "Marshal's Oath",
      unlockTitle: "Marshal's Oath",
      unlockDescription: "Open the sealed utility slot with a command oath that turns the next few exchanges into a killing push.",
      patch: {
        name: "Marshal's Oath",
        energyCost: 1,
        detail: "Battle command. For 3 turns, attacks hit harder and every clean answer grants barrier.",
        buffId: "knight-marshals-oath",
        buffLabel: "Marshal's Oath",
        buffDuration: 3,
        buffApply: { attackPower: 0.18, aoePower: 0.12, blockOnCorrect: 4 },
        buffDescription: "Attacks hit harder and clean answers grant barrier.",
        animationKey: "marshal-oath",
      },
    },
  ],
  wizard: [
    {
      id: "wizard-arc-lash",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Arc Lash",
      unlockTitle: "Arc Lash",
      unlockDescription: "Reforge Strike into a roaming spell that lashes through crowded fights.",
      patch: {
        name: "Arc Lash",
        difficulty: "HARD",
        value: 0.55,
        hits: 3,
        hitTargeting: "RANDOM",
        detail: "Three-hit roaming spell that jumps across random enemies.",
        animationKey: "arc-lash",
      },
    },
    {
      id: "wizard-rune-spear",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Rune Spear",
      unlockTitle: "Rune Spear",
      unlockDescription: "Reforge Strike into a ritual spear built for single-target crit pressure.",
      patch: {
        name: "Rune Spear",
        difficulty: "HARD",
        value: 1.25,
        bonusCritChance: 18,
        detail: "Focused ritual bolt with elevated crit chance against one foe.",
        animationKey: "rune-spear",
      },
    },
    {
      id: "wizard-chain-burst",
      order: 2,
      tier: 2,
      actionId: "aoe",
      name: "Chain Burst",
      unlockTitle: "Chain Burst",
      unlockDescription: "Reforge Sunder Wave into chained detonations that rake the whole formation.",
      patch: {
        name: "Chain Burst",
        value: 0.45,
        hits: 5,
        hitTargeting: "RANDOM",
        detail: "Loose five chained detonations through the enemy formation.",
        animationKey: "chain-burst",
      },
    },
    {
      id: "wizard-restoration-sigil",
      order: 3,
      tier: 3,
      actionId: "util",
      name: "Restoration Sigil",
      unlockTitle: "Restoration Sigil",
      unlockDescription: "Open the sealed utility slot with a recovery sigil that heals and grants a ward.",
      patch: {
        name: "Restoration Sigil",
        energyCost: 2,
        flatHeal: 12,
        healPct: 0.1,
        blockGain: 8,
        detail: "Trace a recovery sigil to heal yourself and gain barrier.",
        animationKey: "restoration-sigil",
      },
    },
    {
      id: "wizard-overchannel",
      order: 4,
      tier: 4,
      actionId: "util",
      name: "Overchannel",
      unlockTitle: "Overchannel",
      unlockDescription: "Open the sealed utility slot with a dangerous trance that floods your next spell cycle with unstable force.",
      patch: {
        name: "Overchannel",
        energyCost: 1,
        detail: "Arcane trance. For 2 turns, HARD spells hit harder and crit much harder.",
        buffId: "wizard-overchannel",
        buffLabel: "Overchannel",
        buffDuration: 2,
        buffApply: { hardActionPower: 0.25, critPowerBonus: 0.3 },
        buffDescription: "HARD spells gain power and devastating crits.",
        animationKey: "overchannel",
      },
    },
  ],
  rogue: [
    {
      id: "rogue-slice-and-dice",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Slice and Dice",
      unlockTitle: "Slice and Dice",
      unlockDescription: "Reforge Strike into a four-hit flurry that jumps through the melee.",
      patch: {
        name: "Slice and Dice",
        value: 0.4,
        hits: 4,
        hitTargeting: "RANDOM",
        detail: "Four rapid cuts that carve through random targets.",
        animationKey: "slice-and-dice",
      },
    },
    {
      id: "rogue-night-bloom",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Night Bloom",
      unlockTitle: "Night Bloom",
      unlockDescription: "Reforge Strike into a tighter assassin string with nastier crit windows.",
      patch: {
        name: "Night Bloom",
        value: 0.56,
        hits: 3,
        bonusCritChance: 16,
        detail: "Focused three-hit cut sequence with elevated crit chance.",
        animationKey: "night-bloom",
      },
    },
    {
      id: "rogue-fan-of-knives",
      order: 2,
      tier: 2,
      actionId: "aoe",
      name: "Fan of Knives",
      unlockTitle: "Fan of Knives",
      unlockDescription: "Reforge Sunder Wave into a blade storm that ricochets through the whole pack.",
      patch: {
        name: "Fan of Knives",
        value: 0.34,
        hits: 5,
        hitTargeting: "RANDOM",
        detail: "Scatter blades into random enemies five times.",
        animationKey: "fan-of-knives",
      },
    },
    {
      id: "rogue-cull-of-the-night",
      order: 3,
      tier: 3,
      actionId: "util",
      name: "Cull of the Night",
      unlockTitle: "Cull of the Night",
      unlockDescription: "Open the sealed utility slot with a killer's hush that makes the next few cuts far deadlier.",
      patch: {
        name: "Cull of the Night",
        energyCost: 1,
        detail: "Assassin stance. For 2 turns, crits hit far harder and quick strikes find kill windows.",
        buffId: "rogue-cull-of-the-night",
        buffLabel: "Cull of the Night",
        buffDuration: 2,
        buffApply: { critPowerBonus: 0.5, quickCritChance: 16 },
        buffDescription: "Crits hit much harder and quick answers crit more often.",
        animationKey: "cull-of-the-night",
      },
    },
  ],
};

export const SKILL_TREES = {
  knight: {
    title: "Knight Disciplines",
    laneOrder: ["vanguard", "bulwark", "execution", "ironclad"],
    lanes: {
      vanguard: {
        id: "vanguard",
        name: "Vanguard",
        theme: "Frontline momentum and shield-led pressure.",
      },
      bulwark: {
        id: "bulwark",
        name: "Bulwark",
        theme: "Barrier play, guard mastery, and attrition.",
      },
      execution: {
        id: "execution",
        name: "Execution",
        theme: "Focused kills, crit discipline, and finishers.",
      },
      ironclad: {
        id: "ironclad",
        name: "Ironclad",
        theme: "Battle-forged conditioning. No lane lock. Always open.",
      },
    },
    nodes: [
      {
        id: "knight-vanguard-shield-rush",
        lane: "vanguard",
        tier: 1,
        label: "Shield Rush",
        description: "Reforge Strike into a shield charge that damages one foe and raises barrier.",
        effect: { techniqueId: "knight-shield-rush" },
      },
      {
        id: "knight-vanguard-war-cry",
        lane: "vanguard",
        tier: 2,
        maxLevel: 3,
        requires: ["knight-vanguard-shield-rush"],
        label: "War-Cry Rhythm",
        description: "Your first attack each turn hits harder after a clean engage.",
        effect: { firstAttackPower: 0.18 },
      },
      {
        id: "knight-vanguard-breaker",
        lane: "vanguard",
        tier: 3,
        maxLevel: 3,
        requires: ["knight-vanguard-war-cry"],
        label: "Breaker March",
        description: "Every correct answer adds extra barrier as you press forward.",
        effect: { blockOnCorrect: 3 },
      },
      {
        id: "knight-vanguard-iron-march",
        lane: "vanguard",
        tier: 4,
        maxLevel: 3,
        requires: ["knight-vanguard-breaker"],
        label: "Iron March",
        description: "Turn momentum into defense. Your opening strike and barrier gain both improve.",
        effect: { blockOnCorrect: 3, firstAttackPower: 0.08 },
      },
      {
        id: "knight-bulwark-form",
        lane: "bulwark",
        tier: 1,
        label: "Bulwark Form",
        description: "Reforge Guard into a heavier stance built for pure barrier play.",
        effect: { techniqueId: "knight-bulwark-form" },
      },
      {
        id: "knight-bulwark-oath",
        lane: "bulwark",
        tier: 2,
        maxLevel: 3,
        requires: ["knight-bulwark-form"],
        label: "Oath Of Iron",
        description: "Your Guard grows sturdier and every defensive play holds longer.",
        effect: { guardPower: 0.22 },
      },
      {
        id: "knight-bulwark-aegis",
        lane: "bulwark",
        tier: 3,
        requires: ["knight-bulwark-oath"],
        label: "Sanctuary Banner",
        description: "Open the sealed utility slot with a banner that heals you and raises cover.",
        effect: { techniqueId: "knight-sanctuary-banner" },
      },
      {
        id: "knight-bulwark-wardbond",
        lane: "bulwark",
        tier: 4,
        maxLevel: 3,
        requires: ["knight-bulwark-aegis"],
        label: "Wardbond",
        description: "Turn every correct answer into more wall. Your defense becomes self-feeding.",
        effect: { guardPower: 0.10, blockOnCorrect: 5 },
      },
      {
        id: "knight-execution-drive",
        lane: "execution",
        tier: 1,
        label: "Execution Drive",
        description: "Reforge Strike into a double-cut finisher for focused single-target burst.",
        effect: { techniqueId: "knight-execution-drive" },
      },
      {
        id: "knight-execution-focus",
        lane: "execution",
        tier: 2,
        maxLevel: 3,
        requires: ["knight-execution-drive"],
        label: "Headsman Focus",
        description: "Your finishing lines hit much harder when they crit.",
        effect: { critPowerBonus: 0.18 },
      },
      {
        id: "knight-execution-momentum",
        lane: "execution",
        tier: 3,
        maxLevel: 1,
        requires: ["knight-execution-focus"],
        label: "Marshal's Oath",
        description: "Open the sealed utility slot with a command oath. For 3 turns, attacks hit harder and clean answers raise barrier.",
        effect: { techniqueId: "knight-marshals-oath", firstActionDiscount: 1 },
      },
      {
        id: "knight-execution-death-sentence",
        lane: "execution",
        tier: 4,
        maxLevel: 3,
        requires: ["knight-execution-momentum"],
        label: "Death Sentence",
        description: "Turn crits and your ultimate into true finishing blows.",
        effect: { critPowerBonus: 0.12, ultimatePowerBonus: 0.28 },
      },
      {
        id: "knight-ironclad-war-hardened",
        lane: "ironclad",
        tier: 1,
        maxLevel: 3,
        label: "War-Hardened",
        description: "Battle experience sharpens the very first hit you throw each turn.",
        effect: { firstAttackPower: 0.12 },
      },
      {
        id: "knight-ironclad-veterans-instinct",
        lane: "ironclad",
        tier: 2,
        maxLevel: 3,
        label: "Veteran's Instinct",
        description: "Fast reads open better crit windows through veteran instinct.",
        effect: { quickCritChance: 12 },
      },
      {
        id: "knight-ironclad-holdfast-doctrine",
        lane: "ironclad",
        tier: 3,
        maxLevel: 3,
        requires: ["knight-ironclad-veterans-instinct"],
        label: "Holdfast Doctrine",
        description: "Every clean answer braces the line with extra barrier.",
        effect: { blockOnCorrect: 2 },
      },
      {
        id: "knight-ironclad-crown-guard",
        lane: "ironclad",
        tier: 4,
        maxLevel: 1,
        requires: ["knight-ironclad-holdfast-doctrine"],
        label: "Crown Guard",
        description: "Stand firm. Your Guard toughens and your ultimate arrives sooner.",
        effect: { guardPower: 0.08, ultimateThresholdDelta: -1 },
      },
    ],
  },
  wizard: {
    title: "Wizard Circuits",
    laneOrder: ["stormweaving", "sigilcraft", "cataclysm", "arcana"],
    lanes: {
      stormweaving: {
        id: "stormweaving",
        name: "Stormweaving",
        theme: "Roving arcs, ricochets, and room-wide spell chaos.",
      },
      sigilcraft: {
        id: "sigilcraft",
        name: "Sigilcraft",
        theme: "Precision geometry, ritual focus, and execution lines.",
      },
      cataclysm: {
        id: "cataclysm",
        name: "Cataclysm",
        theme: "Explosive openings, deep reserves, and battle-ending bursts.",
      },
      arcana: {
        id: "arcana",
        name: "Arcana",
        theme: "Universal spell theory. No lane lock. Always open.",
      },
    },
    nodes: [
      {
        id: "wizard-storm-arc-lash",
        lane: "stormweaving",
        tier: 1,
        label: "Arc Lash",
        description: "Reforge Strike into a three-hit roaming spell for crowded fights.",
        effect: { techniqueId: "wizard-arc-lash" },
      },
      {
        id: "wizard-storm-storm-memory",
        lane: "stormweaving",
        tier: 2,
        maxLevel: 3,
        requires: ["wizard-storm-arc-lash"],
        label: "Storm Memory",
        description: "Your HARD spells strike harder once the storm circuit is humming.",
        effect: { hardActionPower: 0.15 },
      },
      {
        id: "wizard-storm-feedback-halo",
        lane: "stormweaving",
        tier: 3,
        maxLevel: 3,
        requires: ["wizard-storm-storm-memory"],
        label: "Feedback Halo",
        description: "Critical spells arc into nearby foes, and your first HARD spell crit each turn refunds energy.",
        effect: { critSplash: 0.28, spellEnergyRefundOnCrit: 1 },
      },
      {
        id: "wizard-storm-tempest-core",
        lane: "stormweaving",
        tier: 4,
        maxLevel: 3,
        requires: ["wizard-storm-feedback-halo"],
        label: "Tempest Core",
        description: "Your storm crits spread farther and tear through nearby enemies.",
        effect: { critSplash: 0.22, hardActionPower: 0.10 },
      },
      {
        id: "wizard-sigil-rune-spear",
        lane: "sigilcraft",
        tier: 1,
        label: "Rune Spear",
        description: "Reforge Strike into a ritual bolt tuned for focused crit windows.",
        effect: { techniqueId: "wizard-rune-spear" },
      },
      {
        id: "wizard-sigil-perfect-geometry",
        lane: "sigilcraft",
        tier: 2,
        maxLevel: 3,
        requires: ["wizard-sigil-rune-spear"],
        label: "Perfect Geometry",
        description: "Fast, clean answers widen the crit window for precision casting.",
        effect: { quickCritChance: 15 },
      },
      {
        id: "wizard-sigil-astral-pin",
        lane: "sigilcraft",
        tier: 3,
        requires: ["wizard-sigil-perfect-geometry"],
        label: "Restoration Sigil",
        description: "Open the sealed utility slot with a sigil that heals you and grants a ward.",
        effect: { techniqueId: "wizard-restoration-sigil" },
      },
      {
        id: "wizard-sigil-grand-sigil",
        lane: "sigilcraft",
        tier: 4,
        maxLevel: 3,
        requires: ["wizard-sigil-astral-pin"],
        label: "Grand Sigil",
        description: "Precision crits land with devastating ritual force.",
        effect: { critPowerBonus: 0.22 },
      },
      {
        id: "wizard-cataclysm-chain-burst",
        lane: "cataclysm",
        tier: 1,
        label: "Chain Burst",
        description: "Reforge Sunder Wave into five chained detonations for packed fights.",
        effect: { techniqueId: "wizard-chain-burst" },
      },
      {
        id: "wizard-cataclysm-starfall-reserve",
        lane: "cataclysm",
        tier: 2,
        maxLevel: 1,
        requires: ["wizard-cataclysm-chain-burst"],
        label: "Starfall Reserve",
        description: "Gain deeper reserves so your spell strings can run longer.",
        effect: { bonusEnergyPerTurn: 1 },
      },
      {
        id: "wizard-cataclysm-furnace-heart",
        lane: "cataclysm",
        tier: 3,
        maxLevel: 3,
        requires: ["wizard-cataclysm-starfall-reserve"],
        label: "Furnace Heart",
        description: "Your first attack spell each turn hits harder, and Arcstorm Nova hits harder too.",
        effect: { firstAttackPower: 0.18, ultimatePowerBonus: 0.25 },
      },
      {
        id: "wizard-cataclysm-endless-fall",
        lane: "cataclysm",
        tier: 4,
        maxLevel: 1,
        requires: ["wizard-cataclysm-furnace-heart"],
        label: "Overchannel",
        description: "Open the sealed utility slot with a volatile trance. For 2 turns, HARD spells hit harder and crit much harder.",
        effect: { techniqueId: "wizard-overchannel", bonusEnergyPerTurn: 1 },
      },
      {
        id: "wizard-arcana-arcane-hunger",
        lane: "arcana",
        tier: 1,
        maxLevel: 3,
        label: "Arcane Hunger",
        description: "Hard casts hit harder as your arcane appetite grows.",
        effect: { hardActionPower: 0.12 },
      },
      {
        id: "wizard-arcana-pattern-sight",
        lane: "arcana",
        tier: 2,
        maxLevel: 3,
        label: "Pattern Sight",
        description: "Quick casts open wider crit windows through sharper pattern reading.",
        effect: { quickCritChance: 12 },
      },
      {
        id: "wizard-arcana-ley-reservoir",
        lane: "arcana",
        tier: 3,
        maxLevel: 1,
        requires: ["wizard-arcana-pattern-sight"],
        label: "Ley Reservoir",
        description: "A hidden reserve of ether grants +1 energy every turn.",
        effect: { bonusEnergyPerTurn: 1 },
      },
      {
        id: "wizard-arcana-axiom-crown",
        lane: "arcana",
        tier: 4,
        maxLevel: 3,
        requires: ["wizard-arcana-ley-reservoir"],
        label: "Axiom Crown",
        description: "Pure theory lets Focus drive deeper spell crits.",
        effect: { focusCritBoost: 0.08 },
      },
    ],
  },
  rogue: {
    title: "Rogue Arts",
    laneOrder: ["blood-dance", "moon-veil", "knivesong", "shadowcraft"],
    lanes: {
      "blood-dance": {
        id: "blood-dance",
        name: "Blood Dance",
        theme: "Flurries, momentum, and escalating combo pressure.",
      },
      "moon-veil": {
        id: "moon-veil",
        name: "Moon Veil",
        theme: "Assassin crit windows and surgical finishers.",
      },
      knivesong: {
        id: "knivesong",
        name: "Knivesong",
        theme: "Thrown steel, flexible tempo, and battlefield spread.",
      },
      shadowcraft: {
        id: "shadowcraft",
        name: "Shadowcraft",
        theme: "Universal rogue conditioning. No lane lock. Always open.",
      },
    },
    nodes: [
      {
        id: "rogue-blood-slice-and-dice",
        lane: "blood-dance",
        tier: 1,
        label: "Slice and Dice",
        description: "Reforge Strike into a roaming flurry that thrives on tempo.",
        effect: { techniqueId: "rogue-slice-and-dice" },
      },
      {
        id: "rogue-blood-crescendo",
        lane: "blood-dance",
        tier: 2,
        maxLevel: 3,
        requires: ["rogue-blood-slice-and-dice"],
        label: "Crescendo",
        description: "Every combo stack adds more damage to your dance.",
        effect: { comboPowerPerStackBonus: 0.04 },
      },
      {
        id: "rogue-blood-butchers-step",
        lane: "blood-dance",
        tier: 3,
        maxLevel: 3,
        requires: ["rogue-blood-crescendo"],
        label: "Butcher's Step",
        description: "Your opening attack hits harder once the rhythm is set.",
        effect: { firstAttackPower: 0.14 },
      },
      {
        id: "rogue-blood-killing-frenzy",
        lane: "blood-dance",
        tier: 4,
        maxLevel: 3,
        requires: ["rogue-blood-butchers-step"],
        label: "Killing Frenzy",
        description: "Combo bites harder and you gain extra energy to keep the assault rolling.",
        effect: { comboPowerPerStackBonus: 0.02, bonusEnergyPerTurn: 1 },
      },
      {
        id: "rogue-moon-night-bloom",
        lane: "moon-veil",
        tier: 1,
        label: "Night Bloom",
        description: "Reforge Strike into a tight assassin string with deadlier crit windows.",
        effect: { techniqueId: "rogue-night-bloom" },
      },
      {
        id: "rogue-moon-grave-precision",
        lane: "moon-veil",
        tier: 2,
        maxLevel: 3,
        requires: ["rogue-moon-night-bloom"],
        label: "Grave Precision",
        description: "Quick answers open wider crit windows under the veil.",
        effect: { quickCritChance: 12 },
      },
      {
        id: "rogue-moon-black-lotus",
        lane: "moon-veil",
        tier: 3,
        maxLevel: 3,
        requires: ["rogue-moon-grave-precision"],
        label: "Cull of the Night",
        description: "Open the sealed utility slot with an assassin stance. For 2 turns, crits hit far harder and quick cuts find kill windows.",
        effect: { techniqueId: "rogue-cull-of-the-night", critPowerBonus: 0.12 },
      },
      {
        id: "rogue-moon-eclipse-mark",
        lane: "moon-veil",
        tier: 4,
        maxLevel: 3,
        requires: ["rogue-moon-black-lotus"],
        label: "Eclipse Mark",
        description: "Every critical hit returns energy so the blade never stops moving.",
        effect: { critPowerBonus: 0.12, critEnergyRefund: 1 },
      },
      {
        id: "rogue-knife-fan-of-knives",
        lane: "knivesong",
        tier: 1,
        label: "Fan of Knives",
        description: "Reforge Sunder Wave into a thrown storm that ricochets through the whole field.",
        effect: { techniqueId: "rogue-fan-of-knives" },
      },
      {
        id: "rogue-knife-slipstream",
        lane: "knivesong",
        tier: 2,
        maxLevel: 1,
        requires: ["rogue-knife-fan-of-knives"],
        label: "Slipstream",
        description: "Your first action each turn costs less and slips neatly into the combo.",
        effect: { firstActionDiscount: 1 },
      },
      {
        id: "rogue-knife-returning-storm",
        lane: "knivesong",
        tier: 3,
        maxLevel: 1,
        requires: ["rogue-knife-slipstream"],
        label: "Returning Storm",
        description: "Misses no longer shatter your rhythm outright.",
        effect: { softComboBreak: true },
      },
      {
        id: "rogue-knife-storm-fugue",
        lane: "knivesong",
        tier: 4,
        maxLevel: 3,
        requires: ["rogue-knife-returning-storm"],
        label: "Storm Fugue",
        description: "Your hard knife arts spread damage across the whole fight.",
        effect: { hardActionPower: 0.15, critSplash: 0.15 },
      },
      {
        id: "rogue-shadowcraft-light-step",
        lane: "shadowcraft",
        tier: 1,
        maxLevel: 1,
        label: "Light Step",
        description: "Practiced movement makes your first action each turn easier to play.",
        effect: { firstActionDiscount: 1 },
      },
      {
        id: "rogue-shadowcraft-blade-sense",
        lane: "shadowcraft",
        tier: 2,
        maxLevel: 3,
        label: "Blade Sense",
        description: "Fast reads open deadlier crit chances through blade instinct.",
        effect: { quickCritChance: 12 },
      },
      {
        id: "rogue-shadowcraft-cutpurse-instinct",
        lane: "shadowcraft",
        tier: 3,
        maxLevel: 3,
        requires: ["rogue-shadowcraft-blade-sense"],
        label: "Cutpurse Instinct",
        description: "The first opening you spot each turn takes extra damage.",
        effect: { firstAttackPower: 0.12 },
      },
      {
        id: "rogue-shadowcraft-vanishing-point",
        lane: "shadowcraft",
        tier: 4,
        maxLevel: 1,
        requires: ["rogue-shadowcraft-cutpurse-instinct"],
        label: "Vanishing Point",
        description: "A stumble no longer ruins the whole pattern. Misses only cut combo in half.",
        effect: { softComboBreak: true },
      },
    ],
  },
};

export const REST_TRAINING_FALLBACKS = {
  knight: {
    id: "knight-war-drill",
    title: "War Drill",
    description: "Gain +1 STR and +1 VIT.",
    effect: { stats: { str: 1, vit: 1 } },
  },
  wizard: {
    id: "wizard-ritual-study",
    title: "Ritual Study",
    description: "Gain +1 STR and +1 FOCUS.",
    effect: { stats: { str: 1, focus: 1 } },
  },
  rogue: {
    id: "rogue-shadow-drill",
    title: "Shadow Drill",
    description: "Gain +1 VIT and +1 FOCUS.",
    effect: { stats: { vit: 1, focus: 1 } },
  },
};

const ACT_FLOOR_TEMPLATE = [
  { count: 1, types: [NODE_TYPES.MONSTER] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.EVENT] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.SHOP] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.ELITE] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.EVENT, NODE_TYPES.SHOP] },
  { count: 2, types: [NODE_TYPES.TREASURE, NODE_TYPES.MONSTER] },
  { count: 3, types: [NODE_TYPES.MONSTER, NODE_TYPES.ELITE, NODE_TYPES.SHOP] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.EVENT, NODE_TYPES.ELITE] },
  { count: 2, types: [NODE_TYPES.REST, NODE_TYPES.MONSTER] },
  { count: 1, types: [NODE_TYPES.BOSS] },
];

export const FLOOR_RULES = Array.from({ length: MAP_HEIGHT }, (_, floor) => {
  const template = ACT_FLOOR_TEMPLATE[floor % ACT_LENGTH];
  return {
    floor,
    count: template.count,
    types: [...template.types],
  };
});

export const RELICS = [
  {
    id: "quick-slate",
    name: "Quick Slate",
    rarity: "COMMON",
    asset: "./assets/relics/relic-quick-slate.png",
    description: "Fast answers carve a wider crit window. Strike first, strike true.",
    apply: { quickCritChance: 15 },
  },
  {
    id: "iron-theorem",
    name: "Iron Theorem",
    rarity: "COMMON",
    asset: "./assets/relics/relic-iron-theorem.png",
    description: "Every correct answer plates you in 5 block.",
    apply: { blockOnCorrect: 5 },
  },
  {
    id: "scholar-spark",
    name: "Scholar Spark",
    rarity: "RARE",
    asset: "./assets/relics/relic-scholar-spark.png",
    description: "Hard skills crackle with 20% more power.",
    apply: { hardActionPower: 0.2 },
  },
  {
    id: "assassin-abacus",
    name: "Assassin Abacus",
    rarity: "RARE",
    asset: "./assets/relics/relic-assassin-abacus.png",
    description: "Critical hits spill damage into the rest of the room.",
    apply: { critSplash: 0.35 },
  },
  {
    id: "emerald-script",
    name: "Emerald Script",
    rarity: "COMMON",
    asset: "./assets/relics/relic-emerald-script.png",
    description: "Every healing tonic restores 20% more health.",
    apply: { potionHealPower: 0.2 },
  },
  {
    id: "arcane-engine",
    name: "Arcane Engine",
    rarity: "EPIC",
    description: "Quick spell bursts land with 25% more crit power.",
    apply: { critPowerBonus: 0.25 },
  },
  {
    id: "rogue-loop",
    name: "Rogue Loop",
    rarity: "RARE",
    description: "Misses only cut combo in half instead of breaking it outright.",
    apply: { softComboBreak: true },
  },
  {
    id: "vital-reserve",
    name: "Vital Reserve",
    rarity: "COMMON",
    description: "Rest sites restore 15% more of your max HP.",
    apply: { bonusRestHeal: 0.15 },
  },
  {
    id: "merchant-ledger",
    name: "Merchant Ledger",
    rarity: "COMMON",
    description: "Quartermaster prices fall by 20%.",
    apply: { shopDiscount: 0.2 },
  },
  {
    id: "focus-prism",
    name: "Focus Prism",
    rarity: "EPIC",
    description: "Focus adds more weight to critical damage.",
    apply: { focusCritBoost: 0.1 },
  },
  {
    id: "stability-glyph",
    name: "Stability Glyph",
    rarity: "RARE",
    description: "Your ultimate readies 2 energy sooner.",
    apply: { ultimateThresholdDelta: -2 },
  },
  {
    id: "battery-core",
    name: "Battery Core",
    rarity: "EPIC",
    description: "Gain +1 energy at the start of every turn.",
    apply: { bonusEnergyPerTurn: 1 },
  },
  {
    id: "tempo-sigil",
    name: "Tempo Sigil",
    rarity: "RARE",
    description: "Your first action each turn costs 1 less energy.",
    apply: { firstActionDiscount: 1 },
  },
  {
    id: "guardian-circuit",
    name: "Guardian Circuit",
    rarity: "UNCOMMON",
    description: "Guard grants 18% more barrier, and restoration arts heal 4 extra HP.",
    apply: { guardPower: 0.18, restorationHealFlat: 4 },
  },
  {
    id: "combo-censer",
    name: "Combo Censer",
    rarity: "UNCOMMON",
    description: "Each combo stack grants 2% more power.",
    apply: { comboPowerPerStackBonus: 0.02 },
  },
  {
    id: "war-drum",
    name: "War Drum",
    rarity: "LEGENDARY",
    description: "Your first attack each turn hits 35% harder.",
    apply: { firstAttackPower: 0.35 },
  },
  {
    id: "brass-bulwark",
    name: "Brass Bulwark",
    rarity: "COMMON",
    description: "Enter each battle with 8 extra block already raised.",
    apply: { battleStartBlock: 8 },
  },
  {
    id: "field-bandage",
    name: "Field Bandage",
    rarity: "COMMON",
    description: "Every successful Guard also restores 4 HP.",
    apply: { guardHealOnCorrect: 4 },
  },
  {
    id: "cinder-charm",
    name: "Cinder Charm",
    rarity: "COMMON",
    description: "AOE skills hit 14% harder.",
    apply: { aoePower: 0.14 },
  },
  {
    id: "duelist-thread",
    name: "Duelist Thread",
    rarity: "COMMON",
    description: "Single-target attacks hit 14% harder.",
    apply: { attackPower: 0.14 },
  },
  {
    id: "quarter-seal",
    name: "Quarter Seal",
    rarity: "COMMON",
    description: "Victory and treasure gold increase by 18%.",
    apply: { spoilGoldPct: 0.18 },
  },
  {
    id: "herbal-satchel",
    name: "Herbal Satchel",
    rarity: "COMMON",
    description: "Combat victories roll 1 extra herb drop.",
    apply: { bonusHerbDrops: 1 },
  },
  {
    id: "storm-phial",
    name: "Storm Phial",
    rarity: "UNCOMMON",
    description: "Blue tonics restore 1 extra energy.",
    apply: { potionEnergyBonus: 1 },
  },
  {
    id: "raven-banner",
    name: "Raven Banner",
    rarity: "UNCOMMON",
    description: "Start each battle at Combo 1.",
    apply: { battleStartCombo: 1 },
  },
  {
    id: "glass-compass",
    name: "Glass Compass",
    rarity: "UNCOMMON",
    description: "Start each battle with 1 bonus opening energy.",
    apply: { openingTurnEnergy: 1 },
  },
  {
    id: "hearth-sigil",
    name: "Hearth Sigil",
    rarity: "UNCOMMON",
    description: "Restoration arts heal 18% more, and healing tonics heal 10% more.",
    apply: { restorationHealPower: 0.18, potionHealPower: 0.1 },
  },
  {
    id: "soul-prism",
    name: "Soul Prism",
    rarity: "RARE",
    description: "Ultimates ready 1 energy sooner and hit 16% harder.",
    apply: { ultimateThresholdDelta: -1, ultimatePowerBonus: 0.16 },
  },
  {
    id: "night-market-coin",
    name: "Night Market Coin",
    rarity: "RARE",
    description: "Victory and treasure gold increase by 15%, and shop prices fall by 12%.",
    apply: { spoilGoldPct: 0.15, shopDiscount: 0.12 },
  },
  {
    id: "forked-fang",
    name: "Forked Fang",
    rarity: "RARE",
    description: "AOE skills hit 10% harder, and crits spill 15% splash damage.",
    apply: { aoePower: 0.1, critSplash: 0.15 },
  },
  {
    id: "gale-cutters",
    name: "Gale Cutters",
    rarity: "RARE",
    description: "Single-target attacks hit 12% harder, and your first crit each turn refunds 1 energy.",
    apply: { attackPower: 0.12, critEnergyRefund: 1 },
  },
  {
    id: "thorn-codex",
    name: "Thorn Codex",
    rarity: "EPIC",
    description: "Guard grants 15% more barrier, every correct answer gains 3 block, and Guard restores 2 HP.",
    apply: { guardPower: 0.15, blockOnCorrect: 3, guardHealOnCorrect: 2 },
  },
  {
    id: "cathedral-battery",
    name: "Cathedral Battery",
    rarity: "LEGENDARY",
    description: "Gain +1 energy every turn and 1 extra energy on the opening turn.",
    apply: { bonusEnergyPerTurn: 1, openingTurnEnergy: 1 },
  },
];

export const ENEMY_ARCHETYPES = {
  MONSTER: [
    { id: "fiend", name: "Spire Fiend", icon: "F", asset: "./assets/enemies/enemy-spire-fiend.png", hp: 78, damage: 8 },
    { id: "fang", name: "Razor Fang", icon: "R", asset: "./assets/enemies/enemy-razor-fang.png", hp: 70, damage: 10 },
    { id: "shade", name: "Cipher Shade", icon: "C", asset: "./assets/enemies/enemy-cipher-shade.png", hp: 62, damage: 11 },
    { id: "brute", name: "Sum Brute", icon: "S", asset: null, hp: 96, damage: 7 },
    { id: "crow", name: "Divide Crow", icon: "D", asset: null, hp: 68, damage: 12 },
    { id: "priest", name: "Fracture Priest", icon: "P", asset: null, hp: 74, damage: 9 },
  ],
  ELITE: [
    { id: "guard", name: "Elite Guard", icon: "G", asset: "./assets/enemies/enemy-elite-guard.png", hp: 190, damage: 14 },
    { id: "warden", name: "Obelisk Warden", icon: "O", asset: "./assets/enemies/enemy-obelisk-warden.png", hp: 220, damage: 12 },
    { id: "disciple", name: "Sigil Disciple", icon: "S", asset: null, hp: 176, damage: 16 },
    { id: "breaker", name: "Vault Breaker", icon: "V", asset: null, hp: 206, damage: 13 },
  ],
  BOSS: [
    { id: "sentinel", name: "Final Sentinel", icon: "B", asset: "./assets/bosses/boss-final-sentinel.png", hp: 820, damage: 26, acts: [1, 2, 3] },
    { id: "gatekeeper", name: "Gatekeeper Colossus", icon: "G", asset: null, hp: 690, damage: 22, acts: [1] },
    { id: "sigil-engine", name: "Sigil Engine", icon: "S", asset: null, hp: 860, damage: 25, acts: [2] },
    { id: "obelisk-heart", name: "Obelisk Heart", icon: "O", asset: null, hp: 980, damage: 30, acts: [3] },
  ],
};

export const BASE_UNLOCKS = {
  starting: {
    spires: ["addition"],
    relics: ["quick-slate", "iron-theorem", "vital-reserve", "merchant-ledger"],
    events: ["whispering-slate", "blood-merchant", "camp-of-echoes", "oracle-flame", "omens-hand", "ember-greenhouse", "wayfinder-cairn"],
    monsters: ["fiend", "fang"],
    elites: ["guard"],
    bosses: ["sentinel"],
  },
  portalArray: [
    {
      tier: 1,
      cost: { emberwood: 2 },
      title: "Ashen Gate",
      description: "A second gate answers the array and the hollow stirs awake.",
      unlocks: {
        spires: ["subtraction"],
      },
    },
    {
      tier: 2,
      cost: { emberwood: 2, thorium: 1 },
      title: "Echo Forge",
      description: "A deeper current is bound into steel and a new road answers.",
      unlocks: {
        spires: ["multiplication"],
      },
    },
    {
      tier: 3,
      cost: { emberwood: 1, thorium: 2 },
      title: "Sanctum Rift",
      description: "The fractured way is cut open and the sanctum can be reached.",
      unlocks: {
        spires: ["division"],
      },
    },
    {
      tier: 4,
      cost: { thorium: 2, eternium: 1 },
      title: "Crown Nexus",
      description: "The roads converge and the crowned ascent reveals itself.",
      unlocks: {
        spires: ["mixed"],
      },
    },
  ],
  archive: [
    {
      tier: 1,
      cost: { emberwood: 2 },
      title: "Hard-Choice Records",
      description: "Older records are unsealed, and stranger bargains begin to answer the climb.",
      unlocks: {
        events: ["shattered-dynamo", "mirror-of-edges", "sealed-vault", "hollow-apothecary", "glass-sanctum"],
      },
    },
    {
      tier: 2,
      cost: { thorium: 2, eternium: 1 },
      title: "Forbidden Routes",
      description: "The black ledgers are opened, drawing in rarer vows and riskier pacts.",
      unlocks: {
        events: ["oath-pyre", "ghost-market", "black-banner", "tally-of-crows"],
      },
    },
  ],
  relicForge: [
    {
      tier: 1,
      cost: { emberwood: 1, thorium: 1 },
      title: "Field Relics",
      description: "The forge begins turning out steadier charms and battle trinkets.",
      unlocks: {
        relics: ["scholar-spark", "emerald-script", "rogue-loop", "guardian-circuit", "combo-censer", "brass-bulwark", "field-bandage", "cinder-charm", "duelist-thread", "quarter-seal", "herbal-satchel", "storm-phial", "raven-banner", "hearth-sigil"],
      },
    },
    {
      tier: 2,
      cost: { thorium: 2, eternium: 1 },
      title: "Mythic Engine",
      description: "The deeper furnaces ignite, drawing forth rarer instruments of power.",
      unlocks: {
        relics: ["assassin-abacus", "arcane-engine", "focus-prism", "stability-glyph", "battery-core", "tempo-sigil", "war-drum", "glass-compass", "soul-prism", "night-market-coin", "forked-fang", "gale-cutters", "thorn-codex", "cathedral-battery"],
      },
    },
  ],
  warRoom: [
    {
      tier: 1,
      cost: { emberwood: 1, thorium: 1 },
      title: "Expanded Patrols",
      description: "Wider patrol paths rouse fresh fiends and harder wardens.",
      unlocks: {
        monsters: ["shade", "brute", "crow"],
        elites: ["warden", "disciple"],
      },
    },
    {
      tier: 2,
      cost: { thorium: 2, eternium: 1 },
      title: "Boss Hunt Orders",
      description: "Ancient hunt marks are restored, and stronger champions answer each act.",
      unlocks: {
        monsters: ["priest"],
        elites: ["breaker"],
        bosses: ["gatekeeper", "sigil-engine", "obelisk-heart"],
      },
    },
  ],
};

export const BASE_BUILDING_ORDER = ["portalArray", "archive", "relicForge", "warRoom"];

export const BASE_BUILDING_LABELS = {
  portalArray: {
    name: "Portal Array",
    short: "Spires",
    description: "Rekindles the dead gates that lead deeper into the frontier.",
  },
  archive: {
    name: "Archive",
    short: "Events",
    description: "Unseals old records, omens, and stranger chambers.",
  },
  relicForge: {
    name: "Relic Forge",
    short: "Relics",
    description: "Coaxes rarer relics and battle charms into the climb.",
  },
  warRoom: {
    name: "War Room",
    short: "Enemies",
    description: "Stirs fiercer denizens, wardens, and throne-beasts.",
  },
};

export const SHOP_TEMPLATE = [
  { id: "upgrade-atk", kind: "ACTION_UPGRADE", actionId: "atk", label: "Sharpen Strike", baseCost: 110 },
  { id: "upgrade-blk", kind: "ACTION_UPGRADE", actionId: "blk", label: "Temper Guard", baseCost: 110 },
  { id: "upgrade-aoe", kind: "ACTION_UPGRADE", actionId: "aoe", label: "Prime Sunder Wave", baseCost: 135 },
  { id: "herb-cache", kind: "HERBS", herbs: { white: 1, yellow: 1, blue: 1 }, label: "Apothecary Cache", baseCost: 120 },
  { id: "stat-focus", kind: "STAT", stat: "focus", label: "Clarity Draught", baseCost: 90 },
  { id: "stat-str", kind: "STAT", stat: "str", label: "Iron Draft", baseCost: 90 },
  { id: "remove-weakness", kind: "REMOVE", label: "Purge Doubt", baseCost: 150 },
];

export const EVENT_TEMPLATES = [
  {
    id: "whispering-slate",
    title: "Whispering Slate",
    text: "A slate of living sigils hums in your hands. Its lesson is simple: commit, and power answers faster.",
    choices: [
      {
        id: "focus-study",
        label: "Study The Glyphs",
        description: "Gain +2 Focus and steady your critical rhythm.",
        effect: { stats: { focus: 2 } },
      },
      {
        id: "temper-hard",
        label: "Hone A Hard Lesson",
        description: "Sharpen your lowest-level HARD action by 1 level.",
        effect: { upgradeLowestHard: 1 },
      },
      {
        id: "leave",
        label: "Move On",
        description: "Leave the slate dark and keep climbing.",
        effect: {},
      },
    ],
  },
  {
    id: "blood-merchant",
    title: "Blood Merchant",
    text: "A masked trader smiles behind red silk. He deals in momentum, and he never takes coin first.",
    choices: [
      {
        id: "pay-blood",
        label: "Trade Blood For Relic",
        description: "Pay 12% max HP and claim a random relic.",
        effect: { loseHpPct: 0.12, randomRelic: true },
      },
      {
        id: "take-gold",
        label: "Take The Payout",
        description: "Pocket the coin and leave with all your blood.",
        effect: { gold: 140 },
      },
      {
        id: "refuse",
        label: "Refuse",
        description: "Refuse the bargain and keep your strength.",
        effect: {},
      },
    ],
  },
  {
    id: "camp-of-echoes",
    title: "Camp Of Echoes",
    text: "An old training ring waits in the dust. Every solved pattern here leaves a mark on the body.",
    choices: [
      {
        id: "strength-drill",
        label: "Hammer Drill",
        description: "Gain +2 STR and +10 max HP.",
        effect: { stats: { str: 2 }, maxHp: 10 },
      },
      {
        id: "recover",
        label: "Recover And Refocus",
        description: "Gain 1 White Herb, 1 Yellow Herb, and +1 Focus.",
        effect: { herbs: { white: 1, yellow: 1 }, stats: { focus: 1 } },
      },
      {
        id: "double-temper",
        label: "Repeat The Forms",
        description: "Upgrade 2 random actions.",
        effect: { upgradeRandomActions: 2 },
      },
    ],
  },
  {
    id: "oracle-flame",
    title: "Oracle Flame",
    text: "A prophetic flame shows the road ahead and asks what kind of legend you mean to become.",
    choices: [
      {
        id: "balanced-growth",
        label: "Take The Whole Measure",
        description: "Gain +1 STR, +1 VIT, and +1 Focus.",
        effect: { stats: { str: 1, vit: 1, focus: 1 } },
      },
      {
        id: "elite-hunter",
        label: "Hunt The Peak",
        description: "Claim a relic and 60 gold.",
        effect: { randomRelic: true, gold: 60 },
      },
      {
        id: "quiet-step",
        label: "Hold A Quiet Step",
        description: "Gain 1 White Herb and 1 Blue Herb, then keep the run steady.",
        effect: { herbs: { white: 1, blue: 1 } },
      },
    ],
  },
  {
    id: "omens-hand",
    title: "Hand Of Omens",
    text: "A hooded broker lays down three carved tokens and offers a best-of-three wager: stone, scroll, and shears.",
    choices: [
      {
        id: "take-the-wager",
        label: "Take The Wager",
        description: "Play best of three. Win a relic and coin. Lose blood if fortune turns.",
        effect: {
          minigameId: "omens-hand",
          onWin: { randomRelic: true, gold: 40 },
          onLose: { loseHpPct: 0.08 },
          onDraw: { gold: 60 },
        },
      },
      {
        id: "keep-walking",
        label: "Keep Walking",
        description: "Leave the broker and keep the climb steady.",
        effect: {},
      },
    ],
  },
  {
    id: "ember-greenhouse",
    title: "Ember Greenhouse",
    text: "Warm glass and emberlight shelter a hidden herb house beneath the stone. Someone kept the frontier's oldest remedies alive down here.",
    choices: [
      {
        id: "gather-the-beds",
        label: "Gather The Beds",
        description: "Take 1 White Herb, 1 Yellow Herb, and 1 Blue Herb.",
        effect: { herbs: { white: 1, yellow: 1, blue: 1 } },
      },
      {
        id: "distill-on-site",
        label: "Distill On Site",
        description: "Bottle 1 White Tonic and 1 Blue Tonic straight from the stills.",
        effect: { potions: { white: 1, blue: 1 } },
      },
      {
        id: "brew-burnroot",
        label: "Brew Burnroot",
        description: "Lose 8% max HP. Bottle 1 Red Tonic for the next crisis.",
        effect: { loseHpPct: 0.08, potions: { red: 1 } },
      },
    ],
  },
  {
    id: "wayfinder-cairn",
    title: "Wayfinder Cairn",
    text: "Route stones, broken compasses, and old chalk marks cover a cairn left by earlier climbers. The dead still teach the living.",
    choices: [
      {
        id: "chart-a-doctrine",
        label: "Chart A Doctrine",
        description: "Gain 1 skill point for your class tree.",
        effect: { skillPoints: 1 },
      },
      {
        id: "pack-the-satchel",
        label: "Pack The Satchel",
        description: "Take 1 White Herb, 1 Yellow Herb, and 1 White Tonic.",
        effect: { herbs: { white: 1, yellow: 1 }, potions: { white: 1 } },
      },
      {
        id: "carve-a-notch",
        label: "Carve A Notch",
        description: "Upgrade your lowest HARD action by 1 level and pocket 40 gold from the marker cache.",
        effect: { upgradeLowestHard: 1, gold: 40 },
      },
    ],
  },
  {
    id: "shattered-dynamo",
    title: "Shattered Dynamo",
    text: "A cracked engine still beats beneath the stone. You can bind its rhythm, but the machine asks for payment first.",
    choices: [
      {
        id: "bind-core",
        label: "Bind The Core",
        description: "Lose 18% max HP. Gain Battery Core and +1 energy each turn.",
        effect: { loseHpPct: 0.18, relicId: "battery-core" },
      },
      {
        id: "carve-tempo",
        label: "Carve The Tempo Sigil",
        description: "Pay 90 gold. Gain Tempo Sigil so your first action each turn costs 1 less.",
        effect: { loseGold: 90, relicId: "tempo-sigil" },
      },
      {
        id: "rupture-shell",
        label: "Rupture The Shell",
        description: "Gain 170 gold, but lose 10% max HP in the blast.",
        effect: { gold: 170, loseHpPct: 0.1 },
      },
    ],
  },
  {
    id: "mirror-of-edges",
    title: "Mirror Of Edges",
    text: "A spectral reflection offers perfect form. It will sharpen one edge of your kit, but only if you accept the cut that comes with it.",
    choices: [
      {
        id: "cut-for-strike",
        label: "Bleed For Precision",
        description: "Lose 14% max HP. Upgrade Strike by 2 levels.",
        effect: { loseHpPct: 0.14, upgradeActionId: "atk", upgradeActionLevels: 2 },
      },
      {
        id: "gold-for-blast",
      label: "Feed The Sunder Wave",
      description: "Pay 80 gold. Upgrade Sunder Wave by 1 level and gain +1 Focus.",
        effect: { loseGold: 80, upgradeActionId: "aoe", upgradeActionLevels: 1, stats: { focus: 1 } },
      },
      {
        id: "look-away",
        label: "Look Away",
        description: "Leave the mirror untouched.",
        effect: {},
      },
    ],
  },
  {
    id: "hollow-apothecary",
    title: "Hollow Apothecary",
    text: "A shuttered apothecary opens only when you knock the right rhythm. Its keeper trades in preserved tonics, risky brews, and field recipes.",
    choices: [
      {
        id: "buy-rare-stock",
        label: "Buy Rare Stock",
        description: "Pay 90 gold. Gain 1 Yellow Tonic, 1 Blue Tonic, and 1 Red Herb.",
        effect: { loseGold: 90, potions: { yellow: 1, blue: 1 }, herbs: { red: 1 } },
      },
      {
        id: "trade-blood-for-tonic",
        label: "Trade Blood For Tonic",
        description: "Lose 10% max HP. Gain 1 Red Tonic and 1 Blue Tonic.",
        effect: { loseHpPct: 0.1, potions: { red: 1, blue: 1 } },
      },
      {
        id: "steal-the-recipes",
        label: "Steal The Recipes",
        description: "Gain 1 skill point, 1 White Herb, and 1 Red Herb before the keeper returns.",
        effect: { skillPoints: 1, herbs: { white: 1, red: 1 } },
      },
    ],
  },
  {
    id: "glass-sanctum",
    title: "Glass Sanctum",
    text: "A buried sanctum of black glass reflects the build you might become. Each reflection offers a different way to polish the climb.",
    choices: [
      {
        id: "perfect-the-hand",
        label: "Perfect The Hand",
        description: "Lose 8% max HP. Upgrade 2 random actions.",
        effect: { loseHpPct: 0.08, upgradeRandomActions: 2 },
      },
      {
        id: "bottle-the-light",
        label: "Bottle The Light",
        description: "Gain 1 Blue Tonic, 1 Yellow Tonic, and +1 Focus.",
        effect: { potions: { blue: 1, yellow: 1 }, stats: { focus: 1 } },
      },
      {
        id: "cut-the-prism",
        label: "Cut The Prism",
        description: "Lose 12% max HP. Claim a random relic from the live pool.",
        effect: { loseHpPct: 0.12, randomRelic: true },
      },
    ],
  },
  {
    id: "sealed-vault",
    title: "Sealed Vault",
    text: "A pressure door grinds open just enough to tempt you. The Obelisk makes it clear: every prize here costs blood or coin.",
    choices: [
      {
        id: "break-lock",
        label: "Break The Lock",
        description: "Lose 22% max HP and seize a random relic.",
        effect: { loseHpPct: 0.22, randomRelic: true },
      },
      {
        id: "pay-mechanism",
        label: "Prime The Mechanism",
        description: "Pay 120 gold. Gain Stability Glyph and upgrade Guard by 1 level.",
        effect: { loseGold: 120, relicId: "stability-glyph", upgradeActionId: "blk", upgradeActionLevels: 1 },
      },
      {
        id: "take-the-coin",
        label: "Take The Coin",
        description: "Gain 220 gold, but lose 8% max HP escaping the trap.",
        effect: { gold: 220, loseHpPct: 0.08 },
      },
    ],
  },
  {
    id: "black-banner",
    title: "Black Banner",
    text: "A war-banner hangs unburned in still air. It answers only when a legend stands beneath it and names what must awaken.",
    choices: [
      {
        id: "take-the-rite",
        label: "Take The Rite",
        description: "Claim the banner's discipline and open a stronger utility art.",
        effect: {},
      },
      {
        id: "wake-the-seal",
        label: "Wake The Seal",
        description: "Awaken your sealed ultimate for this climb.",
        effect: { unlockUltimate: true },
      },
      {
        id: "carve-doctrine",
        label: "Carve Doctrine",
        description: "Gain 1 skill point and sharpen one signature art.",
        effect: { skillPoints: 1 },
      },
    ],
  },
  {
    id: "oath-pyre",
    title: "Oath Pyre",
    text: "An ancient pyre burns with promises. You may swear yourself to force, precision, or endurance, but every vow demands a visible sacrifice.",
    choices: [
      {
        id: "vow-force",
        label: "Swear Force",
        description: "Lose 15% max HP. Gain +3 STR.",
        effect: { loseHpPct: 0.15, stats: { str: 3 } },
      },
      {
        id: "vow-precision",
        label: "Swear Precision",
        description: "Lose 15% max HP. Gain +3 Focus.",
        effect: { loseHpPct: 0.15, stats: { focus: 3 } },
      },
      {
        id: "vow-endurance",
        label: "Swear Endurance",
        description: "Pay 110 gold. Gain +2 VIT and an apothecary bundle.",
        effect: { loseGold: 110, stats: { vit: 2 }, herbs: { white: 1, yellow: 1 } },
      },
    ],
  },
  {
    id: "tally-of-crows",
    title: "Tally Of Crows",
    text: "A murder of ink-black crows circles a ledger nailed to stone. Each mark promises profit, but every promise here comes with teeth.",
    choices: [
      {
        id: "buy-the-ledger",
        label: "Buy The Ledger",
        description: "Pay 90 gold. Gain Quarter Seal and turn future spoils into fatter purses.",
        effect: { loseGold: 90, relicId: "quarter-seal" },
      },
      {
        id: "mark-the-kill-list",
        label: "Mark The Kill List",
        description: "Gain 1 skill point, upgrade your lowest HARD action, and pocket 1 Red Herb.",
        effect: { skillPoints: 1, upgradeLowestHard: 1, herbs: { red: 1 } },
      },
      {
        id: "take-the-ransom",
        label: "Take The Ransom",
        description: "Claim blackmail coin, but lose 10% max HP escaping the bargain.",
        effect: { gold: 180, loseHpPct: 0.1 },
      },
    ],
  },
  {
    id: "ghost-market",
    title: "Ghost Market",
    text: "A silent bazaar appears between floors. Its wares are exceptional, but the merchants never accept a simple price.",
    choices: [
      {
        id: "buy-prism",
        label: "Buy The Prism",
        description: "Pay 130 gold. Gain Focus Prism.",
        effect: { loseGold: 130, relicId: "focus-prism" },
      },
      {
        id: "steal-ledger",
        label: "Steal The Ledger",
        description: "Lose 20% max HP. Gain Merchant Ledger and 80 gold.",
        effect: { loseHpPct: 0.2, relicId: "merchant-ledger", gold: 80 },
      },
      {
        id: "sell-a-memory",
        label: "Sell A Memory",
        description: "Upgrade your lowest HARD action, then lose 10% max HP.",
        effect: { upgradeLowestHard: 1, loseHpPct: 0.1 },
      },
    ],
  },
];

export const TRAINING_REWARDS = [
  {
    id: "talent-spark",
    kind: "SKILL_POINT",
    amount: 1,
    label: "Talent Ember",
    description: "Bank 1 skill point for your class tree.",
  },
  {
    id: "camp-drill",
    kind: "SKILL_POINT",
    amount: 1,
    label: "War Doctrine",
    description: "Gain 1 skill point and refine your discipline at the next opening.",
  },
  {
    id: "strike-drill",
    kind: "ACTION",
    actionId: "atk",
    label: "Sharpen Strike",
    description: "Upgrade Strike by 1 level.",
  },
  {
    id: "guard-drill",
    kind: "ACTION",
    actionId: "blk",
    label: "Temper Guard",
    description: "Upgrade Guard by 1 level.",
  },
  {
    id: "blast-drill",
    kind: "ACTION",
    actionId: "aoe",
    label: "Prime Sunder Wave",
    description: "Upgrade Sunder Wave by 1 level.",
  },
  {
    id: "herb-bundle",
    kind: "HERBS",
    herbs: { white: 1, blue: 1 },
    label: "Apothecary Bundle",
    description: "Gain one White Herb and one Blue Herb.",
  },
  {
    id: "focus-drill",
    kind: "STAT",
    stat: "focus",
    amount: 2,
    label: "Keen Study",
    description: "Gain +2 Focus.",
  },
  {
    id: "strength-drill",
    kind: "STAT",
    stat: "str",
    amount: 2,
    label: "Iron Lesson",
    description: "Gain +2 STR.",
  },
  {
    id: "vital-drill",
    kind: "STAT",
    stat: "vit",
    amount: 1,
    label: "Stoneblood Drill",
    description: "Gain +1 VIT and +10 max HP.",
  },
  {
    id: "field-rations",
    kind: "HERBS",
    herbs: { yellow: 1, red: 1 },
    label: "Field Satchel",
    description: "Gain one Yellow Herb and one Red Herb.",
  },
  {
    id: "gold-cache",
    kind: "GOLD",
    amount: 90,
    label: "Smuggled Cache",
    description: "Gain 90 extra gold.",
  },
];

export const MINIGAME_TEMPLATES = {
  "omens-hand": {
    id: "omens-hand",
    title: "Hand Of Omens",
    subtitle: "Best of three. Stone breaks Shears, Shears cut Scroll, Scroll binds Stone.",
    type: "RPS",
    targetWins: 2,
    moves: [
      { id: "stone", label: "Stone", beats: "shears" },
      { id: "scroll", label: "Scroll", beats: "stone" },
      { id: "shears", label: "Shears", beats: "scroll" },
    ],
  },
};

export const SCREEN = {
  HUB: "HUB",
  MAP: "MAP",
  BATTLE: "BATTLE",
  EVENT: "EVENT",
  MINIGAME: "MINIGAME",
  TREASURE: "TREASURE",
  SHOP: "SHOP",
  REST: "REST",
  VICTORY: "VICTORY",
  RUN_REPORT: "RUN_REPORT",
  GAMEOVER: "GAMEOVER",
};
