export const APP_KEY = "the_obelisk_prototype_v1";
export const MAP_HEIGHT = 30;
export const ACT_LENGTH = 10;
export const ACT_COUNT = 3;
export const BASE_TIME_LIMIT = 8000;
export const ACT_TIME_LIMITS = [12000, 10000, BASE_TIME_LIMIT];
export const QUICK_WINDOW_MS = 3000;
export const BASE_ENERGY_PER_TURN = 3;
export const BASE_ULTIMATE_CHARGE_REQUIRED = 10;

export const NODE_TYPES = {
  MONSTER: "MONSTER",
  ELITE: "ELITE",
  EVENT: "EVENT",
  REST: "REST",
  TREASURE: "TREASURE",
  SHOP: "SHOP",
  BOSS: "BOSS",
};

export const NODE_ICONS = {
  MONSTER: "M",
  ELITE: "E",
  EVENT: "?",
  REST: "R",
  TREASURE: "T",
  SHOP: "S",
  BOSS: "B",
};

export const NODE_ASSETS = {
  MONSTER: "./assets/nodes/node-monster.png",
  ELITE: "./assets/nodes/node-elite.png",
  EVENT: "./assets/nodes/node-event.png",
  REST: "./assets/nodes/node-rest.png",
  TREASURE: "./assets/nodes/node-treasure.png",
  SHOP: "./assets/nodes/node-shop.png",
  BOSS: "./assets/nodes/node-boss.png",
};

export const LEGENDS = [
  {
    id: "knight",
    name: "Knight",
    icon: "K",
    asset: "./assets/legends/legend-knight-portrait.png",
    color: "legend-knight",
    description: "The Bulwark of the Frontier.",
    hp: 120,
    stats: { str: 10, vit: 12, focus: 5 },
    startingBlock: 20,
    passive: "Starts each battle with bonus barrier.",
  },
  {
    id: "wizard",
    name: "Wizard",
    icon: "W",
    asset: "./assets/legends/legend-wizard-portrait.png",
    color: "legend-wizard",
    description: "Master of volatile equations.",
    hp: 80,
    stats: { str: 14, vit: 6, focus: 10 },
    startingBlock: 0,
    passive: "Hard actions hit much harder when answered quickly.",
  },
  {
    id: "rogue",
    name: "Rogue",
    icon: "R",
    asset: "./assets/legends/legend-rogue-portrait.png",
    color: "legend-rogue",
    description: "Death by a thousand cuts.",
    hp: 100,
    stats: { str: 8, vit: 8, focus: 14 },
    startingBlock: 0,
    passive: "Combo and critical tempo stay online longer.",
  },
];

export const SPIRES = [
  {
    id: "addition",
    name: "Starfall Spire",
    symbol: "+",
    asset: "./assets/spires/spire-addition-emblem.png",
    description: "An addition-bound ascent where totals swell with each act.",
  },
  {
    id: "subtraction",
    name: "Ashen Hollow",
    symbol: "-",
    asset: "./assets/spires/spire-subtraction-emblem.png",
    description: "A subtraction-forged climb built on clean cuts and ruthless differences.",
  },
  {
    id: "multiplication",
    name: "Forge of Echoes",
    symbol: "*",
    asset: "./assets/spires/spire-multiplication-emblem.png",
    description: "A multiplication route of explosive scaling and high-risk burst math.",
  },
  {
    id: "division",
    name: "The Split Sanctum",
    symbol: "/",
    asset: "./assets/spires/spire-division-emblem.png",
    description: "A division-carved tower demanding precise reads and clean integer answers.",
  },
  {
    id: "mixed",
    name: "The Obelisk Crown",
    symbol: "MIX",
    asset: "./assets/spires/spire-mixed-emblem.png",
    description: "A crowned ascent whose lessons widen as the summit nears.",
  },
];

export const MATERIALS = {
  emberwood: {
    id: "emberwood",
    name: "Emberwood",
    short: "Emberwood",
    rarity: "UNCOMMON",
    description: "Smoldering timber cut from the frontier's oldest siege groves. The base uses it to frame gates, archives, and war tables.",
  },
  thorium: {
    id: "thorium",
    name: "Thorium",
    short: "Thorium",
    rarity: "RARE",
    description: "Dense runic metal pried from elite vaultworks. It stabilizes spire portals, forge rigs, and deep combat chambers.",
  },
  eternium: {
    id: "eternium",
    name: "Eternium",
    short: "Eternium",
    rarity: "LEGENDARY",
    description: "Mythic star-metal recovered from the hardest bosses. Every fragment can redefine what future runs are allowed to contain.",
  },
};

export const HERBS = {
  white: {
    id: "white",
    name: "White Herb",
    short: "White",
    rarity: "COMMON",
    description: "A pale field herb used in the weakest recovery brews.",
  },
  yellow: {
    id: "yellow",
    name: "Yellow Herb",
    short: "Yellow",
    rarity: "UNCOMMON",
    description: "A sun-cured stem used for stronger restorative tonics.",
  },
  red: {
    id: "red",
    name: "Red Herb",
    short: "Red",
    rarity: "RARE",
    description: "A fierce scarlet herb prized for deep healing brews.",
  },
  blue: {
    id: "blue",
    name: "Blue Herb",
    short: "Blue",
    rarity: "RARE",
    description: "A cold arcane sprig used in brews that restore energy.",
  },
};

export const POTIONS = {
  white: {
    id: "white",
    herbId: "white",
    name: "White Tonic",
    short: "W",
    kind: "HEAL",
    healPct: 0.14,
    description: "Restore 14% max HP.",
  },
  yellow: {
    id: "yellow",
    herbId: "yellow",
    name: "Yellow Tonic",
    short: "Y",
    kind: "HEAL",
    healPct: 0.21,
    description: "Restore 21% max HP.",
  },
  red: {
    id: "red",
    herbId: "red",
    name: "Red Tonic",
    short: "R",
    kind: "HEAL",
    healPct: 0.28,
    description: "Restore 28% max HP.",
  },
  blue: {
    id: "blue",
    herbId: "blue",
    name: "Blue Tonic",
    short: "B",
    kind: "ENERGY",
    energyRestore: 1,
    description: "Restore 1 energy in battle.",
  },
};

export const BASE_ACTIONS = [
  { id: "atk", name: "Strike", type: "ATK", value: 1.0, baseValue: 1.0, level: 1, energyCost: 1, color: "action-attack", difficulty: "EASY", hotkey: "A", detail: "A clean, reliable hit into one target." },
  { id: "blk", name: "Guard", type: "DEF", value: 1.2, baseValue: 1.2, level: 1, energyCost: 1, color: "action-guard", difficulty: "EASY", hotkey: "S", detail: "Turn a correct answer into solid barrier." },
  { id: "aoe", name: "Sunder Wave", type: "AOE", value: 0.7, baseValue: 0.7, level: 1, energyCost: 2, color: "action-aoe", difficulty: "HARD", hotkey: "D", detail: "Break the line with a hard answer that hits every foe." },
  { id: "util", name: "Sealed Art", type: "UTILITY", value: 0, baseValue: 0, level: 1, energyCost: 2, color: "action-heal", difficulty: "HARD", hotkey: "F", detail: "A sealed utility discipline. Unlock a restoration art to open this slot.", requiresUnlock: "utilitySlotUnlocked" },
];

export const ULTIMATES = {
  knight: {
    id: "ult-knight",
    name: "Guardian Bash",
    legendId: "knight",
    type: "ULTIMATE",
    difficulty: "HARD",
    hotkey: "G",
    color: "action-ultimate-knight",
    detail: "Heavy bash that stuns the target and restores some barrier.",
    tags: ["TARGET", "STUN", "BLOCK"],
    baseDamage: 1.45,
    blockGain: 18,
    stunTurns: 1,
  },
  wizard: {
    id: "ult-wizard",
    name: "Arcstorm Nova",
    legendId: "wizard",
    type: "ULTIMATE",
    difficulty: "HARD",
    hotkey: "G",
    color: "action-ultimate-wizard",
    detail: "Detonates a huge arcane blast across every enemy.",
    tags: ["AOE", "BURST"],
    baseDamage: 2.3,
  },
  rogue: {
    id: "ult-rogue",
    name: "Shadow Flurry",
    legendId: "rogue",
    type: "ULTIMATE",
    difficulty: "HARD",
    hotkey: "G",
    color: "action-ultimate-rogue",
    detail: "A focused multi-slash finisher with elevated crit chance.",
    tags: ["TARGET", "MULTI", "CRIT"],
    baseDamage: 0.72,
    hits: 3,
    bonusCritChance: 28,
  },
};

export const ACTION_EVOLUTIONS = {
  knight: [
    {
      id: "knight-shield-rush",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Shield Rush",
      unlockTitle: "Shield Rush",
      unlockDescription: "Strike is reforged into a rushing bash that still hits hard while raising barrier.",
      patch: {
        name: "Shield Rush",
        value: 0.9,
        detail: "Crash forward for solid damage and gain 12 block.",
        blockGain: 12,
        animationKey: "shield-rush",
      },
    },
    {
      id: "knight-execution-drive",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Execution Drive",
      unlockTitle: "Execution Drive",
      unlockDescription: "Strike becomes a heavier two-cut finisher built for focused burst and cleaner crits.",
      patch: {
        name: "Execution Drive",
        difficulty: "HARD",
        value: 0.78,
        hits: 2,
        bonusCritChance: 12,
        detail: "Drive two precise cuts into one target with elevated crit chance.",
        animationKey: "execution-drive",
      },
    },
    {
      id: "knight-bulwark-form",
      order: 2,
      tier: 2,
      actionId: "blk",
      name: "Bulwark Form",
      unlockTitle: "Bulwark Form",
      unlockDescription: "Guard becomes a heavier stance that restores a little health while raising barrier.",
      patch: {
        name: "Bulwark Form",
        value: 1.35,
        detail: "Raise heavier barrier and hold the line under pressure.",
        animationKey: "bulwark-form",
      },
    },
    {
      id: "knight-sanctuary-banner",
      order: 3,
      tier: 3,
      actionId: "util",
      name: "Sanctuary Banner",
      unlockTitle: "Sanctuary Banner",
      unlockDescription: "The sealed utility slot opens into a battlefield standard that restores health and steadies the line.",
      patch: {
        name: "Sanctuary Banner",
        energyCost: 2,
        flatHeal: 14,
        healPct: 0.08,
        blockGain: 12,
        detail: "Raise a warding banner to restore health and gain 12 block.",
        animationKey: "sanctuary-banner",
      },
    },
  ],
  wizard: [
    {
      id: "wizard-arc-lash",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Arc Lash",
      unlockTitle: "Arc Lash",
      unlockDescription: "Strike becomes a roaming three-hit spell that dances through crowded formations.",
      patch: {
        name: "Arc Lash",
        difficulty: "HARD",
        value: 0.55,
        hits: 3,
        hitTargeting: "RANDOM",
        detail: "3-hit roaming spell that jumps across random enemies.",
        animationKey: "arc-lash",
      },
    },
    {
      id: "wizard-rune-spear",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Rune Spear",
      unlockTitle: "Rune Spear",
      unlockDescription: "Strike condenses into a ritual spear built to punish one target with precise crit pressure.",
      patch: {
        name: "Rune Spear",
        difficulty: "HARD",
        value: 1.25,
        bonusCritChance: 18,
        detail: "Focused ritual bolt with elevated crit chance.",
        animationKey: "rune-spear",
      },
    },
    {
      id: "wizard-chain-burst",
      order: 2,
      tier: 2,
      actionId: "aoe",
      name: "Chain Burst",
      unlockTitle: "Chain Burst",
      unlockDescription: "Sunder Wave becomes a chained detonation that lashes through the whole formation.",
      patch: {
        name: "Chain Burst",
        value: 0.45,
        hits: 5,
        hitTargeting: "RANDOM",
        detail: "Loose five chained detonations into the enemy formation.",
        animationKey: "chain-burst",
      },
    },
    {
      id: "wizard-restoration-sigil",
      order: 3,
      tier: 3,
      actionId: "util",
      name: "Restoration Sigil",
      unlockTitle: "Restoration Sigil",
      unlockDescription: "The sealed utility slot opens into a recovery sigil that restores health and wraps the caster in a ward.",
      patch: {
        name: "Restoration Sigil",
        energyCost: 2,
        flatHeal: 12,
        healPct: 0.1,
        blockGain: 8,
        detail: "Trace a recovery sigil to restore health and gain 8 block.",
        animationKey: "restoration-sigil",
      },
    },
  ],
  rogue: [
    {
      id: "rogue-slice-and-dice",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Slice and Dice",
      unlockTitle: "Slice and Dice",
      unlockDescription: "Strike becomes a four-hit flurry that carves into random targets.",
      patch: {
        name: "Slice and Dice",
        value: 0.4,
        hits: 4,
        hitTargeting: "RANDOM",
        detail: "Deal 40% weapon damage to random targets 4 times.",
        animationKey: "slice-and-dice",
      },
    },
    {
      id: "rogue-night-bloom",
      order: 1,
      tier: 1,
      actionId: "atk",
      name: "Night Bloom",
      unlockTitle: "Night Bloom",
      unlockDescription: "Strike shifts into a tighter assassin string that hits fewer times but threatens stronger crit bursts.",
      patch: {
        name: "Night Bloom",
        value: 0.56,
        hits: 3,
        bonusCritChance: 16,
        detail: "Drive a focused three-hit cut sequence with elevated crit chance.",
        animationKey: "night-bloom",
      },
    },
    {
      id: "rogue-fan-of-knives",
      order: 2,
      tier: 2,
      actionId: "aoe",
      name: "Fan of Knives",
      unlockTitle: "Fan of Knives",
      unlockDescription: "Sunder Wave becomes a storm of blades that ricochets through the whole pack.",
      patch: {
        name: "Fan of Knives",
        value: 0.34,
        hits: 5,
        hitTargeting: "RANDOM",
        detail: "Scatter blades into random enemies 5 times.",
        animationKey: "fan-of-knives",
      },
    },
  ],
};

export const SKILL_TREES = {
  knight: {
    title: "Knight Disciplines",
    laneOrder: ["vanguard", "bulwark", "execution", "ironclad"],
    lanes: {
      vanguard: {
        id: "vanguard",
        name: "Vanguard",
        theme: "Frontline momentum and shield-led pressure.",
      },
      bulwark: {
        id: "bulwark",
        name: "Bulwark",
        theme: "Barrier play, guard mastery, and attrition.",
      },
      execution: {
        id: "execution",
        name: "Execution",
        theme: "Focused kills, crit discipline, and finishers.",
      },
      ironclad: {
        id: "ironclad",
        name: "Ironclad",
        theme: "Battle-forged conditioning. No lane lock. Always open.",
      },
    },
    nodes: [
      {
        id: "knight-vanguard-shield-rush",
        lane: "vanguard",
        tier: 1,
        label: "Shield Rush",
        description: "Crash into the front line and reforge Strike into a barrier-raising bash.",
        effect: { techniqueId: "knight-shield-rush" },
      },
      {
        id: "knight-vanguard-war-cry",
        lane: "vanguard",
        tier: 2,
        maxLevel: 3,
        requires: ["knight-vanguard-shield-rush"],
        label: "War-Cry Rhythm",
        description: "The first attack each turn hits harder after a clean engage.",
        effect: { firstAttackPower: 0.18 },
      },
      {
        id: "knight-vanguard-breaker",
        lane: "vanguard",
        tier: 3,
        maxLevel: 3,
        requires: ["knight-vanguard-war-cry"],
        label: "Breaker March",
        description: "Each correct answer steadies the line with extra barrier.",
        effect: { blockOnCorrect: 3 },
      },
      {
        id: "knight-vanguard-iron-march",
        lane: "vanguard",
        tier: 4,
        maxLevel: 3,
        requires: ["knight-vanguard-breaker"],
        label: "Iron March",
        description: "Sustained forward pressure compounds: barrier and first-strike power reinforce each other.",
        effect: { blockOnCorrect: 3, firstAttackPower: 0.08 },
      },
      {
        id: "knight-bulwark-form",
        lane: "bulwark",
        tier: 1,
        label: "Bulwark Form",
        description: "Turn Guard into a heavier warding stance built for pure barrier discipline.",
        effect: { techniqueId: "knight-bulwark-form" },
      },
      {
        id: "knight-bulwark-oath",
        lane: "bulwark",
        tier: 2,
        maxLevel: 3,
        requires: ["knight-bulwark-form"],
        label: "Oath Of Iron",
        description: "Guard and barrier effects deepen under disciplined timing.",
        effect: { guardPower: 0.22 },
      },
      {
        id: "knight-bulwark-aegis",
        lane: "bulwark",
        tier: 3,
        requires: ["knight-bulwark-oath"],
        label: "Sanctuary Banner",
        description: "Open the sealed utility slot with a battlefield banner that restores health and raises cover.",
        effect: { techniqueId: "knight-sanctuary-banner" },
      },
      {
        id: "knight-bulwark-wardbond",
        lane: "bulwark",
        tier: 4,
        maxLevel: 3,
        requires: ["knight-bulwark-aegis"],
        label: "Wardbond",
        description: "Mastery of the defensive art: every correct answer now builds the wall as well as raises it.",
        effect: { guardPower: 0.10, blockOnCorrect: 5 },
      },
      {
        id: "knight-execution-drive",
        lane: "execution",
        tier: 1,
        label: "Execution Drive",
        description: "Refine Strike into a double-cut finisher meant to punish single targets.",
        effect: { techniqueId: "knight-execution-drive" },
      },
      {
        id: "knight-execution-focus",
        lane: "execution",
        tier: 2,
        maxLevel: 3,
        requires: ["knight-execution-drive"],
        label: "Headsman Focus",
        description: "Focused finishing lines gain more crit damage.",
        effect: { critPowerBonus: 0.18 },
      },
      {
        id: "knight-execution-momentum",
        lane: "execution",
        tier: 3,
        maxLevel: 1,
        requires: ["knight-execution-focus"],
        label: "Killing Tempo",
        description: "Tight kill windows refund pace through a cheaper opening action.",
        effect: { firstActionDiscount: 1 },
      },
      {
        id: "knight-execution-death-sentence",
        lane: "execution",
        tier: 4,
        maxLevel: 3,
        requires: ["knight-execution-momentum"],
        label: "Death Sentence",
        description: "The executioner's verdict: crit lines carry greater weight and your ultimate becomes a finishing blow of absolute force.",
        effect: { critPowerBonus: 0.12, ultimatePowerBonus: 0.28 },
      },
      {
        id: "knight-ironclad-war-hardened",
        lane: "ironclad",
        tier: 1,
        maxLevel: 3,
        label: "War-Hardened",
        description: "A lifetime of front-line combat sharpens your opening strike every battle.",
        effect: { firstAttackPower: 0.12 },
      },
      {
        id: "knight-ironclad-veterans-instinct",
        lane: "ironclad",
        tier: 2,
        maxLevel: 3,
        label: "Veteran's Instinct",
        description: "Battle-hardened reflexes open tighter crit windows on fast reads.",
        effect: { quickCritChance: 12 },
      },
    ],
  },
  wizard: {
    title: "Wizard Circuits",
    laneOrder: ["stormweaving", "sigilcraft", "cataclysm", "arcana"],
    lanes: {
      stormweaving: {
        id: "stormweaving",
        name: "Stormweaving",
        theme: "Roving arcs, ricochets, and room-wide spell chaos.",
      },
      sigilcraft: {
        id: "sigilcraft",
        name: "Sigilcraft",
        theme: "Precision geometry, ritual focus, and execution lines.",
      },
      cataclysm: {
        id: "cataclysm",
        name: "Cataclysm",
        theme: "Explosive openings, deep reserves, and battle-ending bursts.",
      },
      arcana: {
        id: "arcana",
        name: "Arcana",
        theme: "Universal spell theory. No lane lock. Always open.",
      },
    },
    nodes: [
      {
        id: "wizard-storm-arc-lash",
        lane: "stormweaving",
        tier: 1,
        label: "Arc Lash",
        description: "Strike becomes Arc Lash, a 3-hit roaming spell that lights up crowded fights.",
        effect: { techniqueId: "wizard-arc-lash" },
      },
      {
        id: "wizard-storm-storm-memory",
        lane: "stormweaving",
        tier: 2,
        maxLevel: 3,
        requires: ["wizard-storm-arc-lash"],
        label: "Storm Memory",
        description: "HARD actions gain more force once the storm circuit is active.",
        effect: { hardActionPower: 0.15 },
      },
      {
        id: "wizard-storm-feedback-halo",
        lane: "stormweaving",
        tier: 3,
        maxLevel: 3,
        requires: ["wizard-storm-storm-memory"],
        label: "Feedback Halo",
        description: "Critical spells kick collateral arc damage, and the first HARD spell crit each turn surges energy back into the circuit.",
        effect: { critSplash: 0.28, spellEnergyRefundOnCrit: 1 },
      },
      {
        id: "wizard-storm-tempest-core",
        lane: "stormweaving",
        tier: 4,
        maxLevel: 3,
        requires: ["wizard-storm-feedback-halo"],
        label: "Tempest Core",
        description: "The storm reaches critical mass. Every crit arc tears through adjacent targets with wild residual force.",
        effect: { critSplash: 0.22, hardActionPower: 0.10 },
      },
      {
        id: "wizard-sigil-rune-spear",
        lane: "sigilcraft",
        tier: 1,
        label: "Rune Spear",
        description: "Strike becomes Rune Spear, a ritual bolt tuned for focused crit windows.",
        effect: { techniqueId: "wizard-rune-spear" },
      },
      {
        id: "wizard-sigil-perfect-geometry",
        lane: "sigilcraft",
        tier: 2,
        maxLevel: 3,
        requires: ["wizard-sigil-rune-spear"],
        label: "Perfect Geometry",
        description: "Fast, clean answers widen the crit window for precision casting.",
        effect: { quickCritChance: 15 },
      },
      {
        id: "wizard-sigil-astral-pin",
        lane: "sigilcraft",
        tier: 3,
        requires: ["wizard-sigil-perfect-geometry"],
        label: "Restoration Sigil",
        description: "Open the sealed utility slot with a recovery sigil that restores health and wards the caster.",
        effect: { techniqueId: "wizard-restoration-sigil" },
      },
      {
        id: "wizard-sigil-grand-sigil",
        lane: "sigilcraft",
        tier: 4,
        maxLevel: 3,
        requires: ["wizard-sigil-astral-pin"],
        label: "Grand Sigil",
        description: "Ritual mastery perfected. Every precision crit carries devastating weight.",
        effect: { critPowerBonus: 0.22 },
      },
      {
        id: "wizard-cataclysm-chain-burst",
        lane: "cataclysm",
        tier: 1,
        label: "Chain Burst",
        description: "Sunder Wave becomes Chain Burst, a five-hit detonation storm for packed fights.",
        effect: { techniqueId: "wizard-chain-burst" },
      },
      {
        id: "wizard-cataclysm-starfall-reserve",
        lane: "cataclysm",
        tier: 2,
        maxLevel: 1,
        requires: ["wizard-cataclysm-chain-burst"],
        label: "Starfall Reserve",
        description: "Deep reserves raise energy so the Wizard can sustain longer spell strings.",
        effect: { bonusEnergyPerTurn: 1 },
      },
      {
        id: "wizard-cataclysm-furnace-heart",
        lane: "cataclysm",
        tier: 3,
        maxLevel: 3,
        requires: ["wizard-cataclysm-starfall-reserve"],
        label: "Furnace Heart",
        description: "The first attack spell each turn detonates harder, and Arcstorm Nova tears wider through the room.",
        effect: { firstAttackPower: 0.18, ultimatePowerBonus: 0.25 },
      },
      {
        id: "wizard-cataclysm-endless-fall",
        lane: "cataclysm",
        tier: 4,
        maxLevel: 1,
        requires: ["wizard-cataclysm-furnace-heart"],
        label: "Endless Fall",
        description: "Bottomless reserves keep the chain alive. One more burst, always.",
        effect: { bonusEnergyPerTurn: 1 },
      },
      {
        id: "wizard-arcana-arcane-hunger",
        lane: "arcana",
        tier: 1,
        maxLevel: 3,
        label: "Arcane Hunger",
        description: "Deeper engagement with difficult spells yields extra force on every hard cast.",
        effect: { hardActionPower: 0.12 },
      },
      {
        id: "wizard-arcana-pattern-sight",
        lane: "arcana",
        tier: 2,
        maxLevel: 3,
        label: "Pattern Sight",
        description: "Spell recognition comes faster. Quick casts open wider crit geometry.",
        effect: { quickCritChance: 12 },
      },
    ],
  },
  rogue: {
    title: "Rogue Arts",
    laneOrder: ["blood-dance", "moon-veil", "knivesong", "shadowcraft"],
    lanes: {
      "blood-dance": {
        id: "blood-dance",
        name: "Blood Dance",
        theme: "Flurries, momentum, and escalating combo pressure.",
      },
      "moon-veil": {
        id: "moon-veil",
        name: "Moon Veil",
        theme: "Assassin crit windows and surgical finishers.",
      },
      knivesong: {
        id: "knivesong",
        name: "Knivesong",
        theme: "Thrown steel, flexible tempo, and battlefield spread.",
      },
      shadowcraft: {
        id: "shadowcraft",
        name: "Shadowcraft",
        theme: "Universal rogue conditioning. No lane lock. Always open.",
      },
    },
    nodes: [
      {
        id: "rogue-blood-slice-and-dice",
        lane: "blood-dance",
        tier: 1,
        label: "Slice and Dice",
        description: "Turn Strike into a roaming flurry that escalates with tempo.",
        effect: { techniqueId: "rogue-slice-and-dice" },
      },
      {
        id: "rogue-blood-crescendo",
        lane: "blood-dance",
        tier: 2,
        maxLevel: 3,
        requires: ["rogue-blood-slice-and-dice"],
        label: "Crescendo",
        description: "Every combo stack adds noticeably more damage to the dance.",
        effect: { comboPowerPerStackBonus: 0.04 },
      },
      {
        id: "rogue-blood-butchers-step",
        lane: "blood-dance",
        tier: 3,
        maxLevel: 3,
        requires: ["rogue-blood-crescendo"],
        label: "Butcher's Step",
        description: "Openers hit harder once the rhythm is set.",
        effect: { firstAttackPower: 0.14 },
      },
      {
        id: "rogue-blood-killing-frenzy",
        lane: "blood-dance",
        tier: 4,
        maxLevel: 3,
        requires: ["rogue-blood-butchers-step"],
        label: "Killing Frenzy",
        description: "The dance reaches full rhythm: each stack bites a little harder, and an extra pulse of energy flows in each turn to keep the assault relentless.",
        effect: { comboPowerPerStackBonus: 0.02, bonusEnergyPerTurn: 1 },
      },
      {
        id: "rogue-moon-night-bloom",
        lane: "moon-veil",
        tier: 1,
        label: "Night Bloom",
        description: "Refine Strike into a tight assassin string with deadlier crit windows.",
        effect: { techniqueId: "rogue-night-bloom" },
      },
      {
        id: "rogue-moon-grave-precision",
        lane: "moon-veil",
        tier: 2,
        maxLevel: 3,
        requires: ["rogue-moon-night-bloom"],
        label: "Grave Precision",
        description: "Quick answers open wider crit windows under the veil.",
        effect: { quickCritChance: 12 },
      },
      {
        id: "rogue-moon-black-lotus",
        lane: "moon-veil",
        tier: 3,
        maxLevel: 3,
        requires: ["rogue-moon-grave-precision"],
        label: "Black Lotus",
        description: "Assassin crits bloom into heavier finishers.",
        effect: { critPowerBonus: 0.22 },
      },
      {
        id: "rogue-moon-eclipse-mark",
        lane: "moon-veil",
        tier: 4,
        maxLevel: 3,
        requires: ["rogue-moon-black-lotus"],
        label: "Eclipse Mark",
        description: "The mark of a true assassin: every critical hit returns one energy, letting the blade keep moving without pause.",
        effect: { critPowerBonus: 0.12, critEnergyRefund: 1 },
      },
      {
        id: "rogue-knife-fan-of-knives",
        lane: "knivesong",
        tier: 1,
        label: "Fan of Knives",
        description: "Turn Sunder Wave into a thrown storm that ricochets through the whole field.",
        effect: { techniqueId: "rogue-fan-of-knives" },
      },
      {
        id: "rogue-knife-slipstream",
        lane: "knivesong",
        tier: 2,
        maxLevel: 1,
        requires: ["rogue-knife-fan-of-knives"],
        label: "Slipstream",
        description: "Your first action each turn is easier to thread into the combo.",
        effect: { firstActionDiscount: 1 },
      },
      {
        id: "rogue-knife-returning-storm",
        lane: "knivesong",
        tier: 3,
        maxLevel: 1,
        requires: ["rogue-knife-slipstream"],
        label: "Returning Storm",
        description: "Mistakes no longer shatter your rhythm outright.",
        effect: { softComboBreak: true },
      },
      {
        id: "rogue-knife-storm-fugue",
        lane: "knivesong",
        tier: 4,
        maxLevel: 3,
        requires: ["rogue-knife-returning-storm"],
        label: "Storm Fugue",
        description: "The storm reaches every corner. Hard knives arc with wild spread damage.",
        effect: { hardActionPower: 0.15, critSplash: 0.15 },
      },
      {
        id: "rogue-shadowcraft-light-step",
        lane: "shadowcraft",
        tier: 1,
        maxLevel: 1,
        label: "Light Step",
        description: "Practiced movement flows into the opening move of every battle.",
        effect: { firstActionDiscount: 1 },
      },
      {
        id: "rogue-shadowcraft-blade-sense",
        lane: "shadowcraft",
        tier: 2,
        maxLevel: 3,
        label: "Blade Sense",
        description: "Blade instinct sharpens fast reads into deadlier crit opportunities.",
        effect: { quickCritChance: 12 },
      },
    ],
  },
};

export const REST_TRAINING_FALLBACKS = {
  knight: {
    id: "knight-war-drill",
    title: "War Drill",
    description: "Gain +1 STR and +1 VIT.",
    effect: { stats: { str: 1, vit: 1 } },
  },
  wizard: {
    id: "wizard-ritual-study",
    title: "Ritual Study",
    description: "Gain +1 STR and +1 FOCUS.",
    effect: { stats: { str: 1, focus: 1 } },
  },
  rogue: {
    id: "rogue-shadow-drill",
    title: "Shadow Drill",
    description: "Gain +1 VIT and +1 FOCUS.",
    effect: { stats: { vit: 1, focus: 1 } },
  },
};

const ACT_FLOOR_TEMPLATE = [
  { count: 1, types: [NODE_TYPES.MONSTER] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.EVENT] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.SHOP] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.ELITE] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.EVENT, NODE_TYPES.SHOP] },
  { count: 2, types: [NODE_TYPES.TREASURE, NODE_TYPES.MONSTER] },
  { count: 3, types: [NODE_TYPES.MONSTER, NODE_TYPES.ELITE, NODE_TYPES.SHOP] },
  { count: 2, types: [NODE_TYPES.MONSTER, NODE_TYPES.EVENT, NODE_TYPES.ELITE] },
  { count: 2, types: [NODE_TYPES.REST, NODE_TYPES.MONSTER] },
  { count: 1, types: [NODE_TYPES.BOSS] },
];

export const FLOOR_RULES = Array.from({ length: MAP_HEIGHT }, (_, floor) => {
  const template = ACT_FLOOR_TEMPLATE[floor % ACT_LENGTH];
  return {
    floor,
    count: template.count,
    types: [...template.types],
  };
});

export const RELICS = [
  {
    id: "quick-slate",
    name: "Quick Slate",
    rarity: "COMMON",
    asset: "./assets/relics/relic-quick-slate.png",
    description: "Quick answers gain +15 crit chance.",
    apply: { quickCritChance: 15 },
  },
  {
    id: "iron-theorem",
    name: "Iron Theorem",
    rarity: "COMMON",
    asset: "./assets/relics/relic-iron-theorem.png",
    description: "Gain 5 block after every correct answer.",
    apply: { blockOnCorrect: 5 },
  },
  {
    id: "scholar-spark",
    name: "Scholar Spark",
    rarity: "RARE",
    asset: "./assets/relics/relic-scholar-spark.png",
    description: "Hard actions gain +20% power.",
    apply: { hardActionPower: 0.2 },
  },
  {
    id: "assassin-abacus",
    name: "Assassin Abacus",
    rarity: "RARE",
    asset: "./assets/relics/relic-assassin-abacus.png",
    description: "Critical hits deal splash damage to all enemies.",
    apply: { critSplash: 0.35 },
  },
  {
    id: "emerald-script",
    name: "Emerald Script",
    rarity: "COMMON",
    asset: "./assets/relics/relic-emerald-script.png",
    description: "Healing tonics restore 20% more health.",
    apply: { potionHealPower: 0.2 },
  },
  {
    id: "arcane-engine",
    name: "Arcane Engine",
    rarity: "EPIC",
    description: "Wizard-style quick bursts gain +25 crit power.",
    apply: { critPowerBonus: 0.25 },
  },
  {
    id: "rogue-loop",
    name: "Rogue Loop",
    rarity: "RARE",
    description: "Misses only cut combo in half instead of breaking it.",
    apply: { softComboBreak: true },
  },
  {
    id: "vital-reserve",
    name: "Vital Reserve",
    rarity: "COMMON",
    description: "Rest sites heal an extra 15% max HP.",
    apply: { bonusRestHeal: 0.15 },
  },
  {
    id: "merchant-ledger",
    name: "Merchant Ledger",
    rarity: "COMMON",
    description: "Shop prices are reduced by 20%.",
    apply: { shopDiscount: 0.2 },
  },
  {
    id: "focus-prism",
    name: "Focus Prism",
    rarity: "EPIC",
    description: "Focus contributes more to critical multiplier.",
    apply: { focusCritBoost: 0.1 },
  },
  {
    id: "stability-glyph",
    name: "Stability Glyph",
    rarity: "RARE",
    description: "Your ultimate becomes ready 2 energy sooner.",
    apply: { ultimateThresholdDelta: -2 },
  },
  {
    id: "battery-core",
    name: "Battery Core",
    rarity: "EPIC",
    description: "Gain +1 energy at the start of every turn.",
    apply: { bonusEnergyPerTurn: 1 },
  },
  {
    id: "tempo-sigil",
    name: "Tempo Sigil",
    rarity: "RARE",
    description: "Your first action each turn costs 1 less energy.",
    apply: { firstActionDiscount: 1 },
  },
  {
    id: "guardian-circuit",
    name: "Guardian Circuit",
    rarity: "UNCOMMON",
    description: "Guard gains 18% more barrier, and restoration arts recover 4 extra HP.",
    apply: { guardPower: 0.18, restorationHealFlat: 4 },
  },
  {
    id: "combo-censer",
    name: "Combo Censer",
    rarity: "UNCOMMON",
    description: "Combo grants an extra 2% power per stack.",
    apply: { comboPowerPerStackBonus: 0.02 },
  },
  {
    id: "war-drum",
    name: "War Drum",
    rarity: "LEGENDARY",
    description: "The first attack each turn gains +35% power.",
    apply: { firstAttackPower: 0.35 },
  },
];

export const ENEMY_ARCHETYPES = {
  MONSTER: [
    { id: "fiend", name: "Spire Fiend", icon: "F", asset: "./assets/enemies/enemy-spire-fiend.png", hp: 78, damage: 8 },
    { id: "fang", name: "Razor Fang", icon: "R", asset: "./assets/enemies/enemy-razor-fang.png", hp: 70, damage: 10 },
    { id: "shade", name: "Cipher Shade", icon: "C", asset: "./assets/enemies/enemy-cipher-shade.png", hp: 62, damage: 11 },
    { id: "brute", name: "Sum Brute", icon: "S", asset: null, hp: 96, damage: 7 },
    { id: "crow", name: "Divide Crow", icon: "D", asset: null, hp: 68, damage: 12 },
    { id: "priest", name: "Fracture Priest", icon: "P", asset: null, hp: 74, damage: 9 },
  ],
  ELITE: [
    { id: "guard", name: "Elite Guard", icon: "G", asset: "./assets/enemies/enemy-elite-guard.png", hp: 190, damage: 14 },
    { id: "warden", name: "Obelisk Warden", icon: "O", asset: "./assets/enemies/enemy-obelisk-warden.png", hp: 220, damage: 12 },
    { id: "disciple", name: "Sigil Disciple", icon: "S", asset: null, hp: 176, damage: 16 },
    { id: "breaker", name: "Vault Breaker", icon: "V", asset: null, hp: 206, damage: 13 },
  ],
  BOSS: [
    { id: "sentinel", name: "Final Sentinel", icon: "B", asset: "./assets/bosses/boss-final-sentinel.png", hp: 820, damage: 26, acts: [1, 2, 3] },
    { id: "gatekeeper", name: "Gatekeeper Colossus", icon: "G", asset: null, hp: 690, damage: 22, acts: [1] },
    { id: "sigil-engine", name: "Sigil Engine", icon: "S", asset: null, hp: 860, damage: 25, acts: [2] },
    { id: "obelisk-heart", name: "Obelisk Heart", icon: "O", asset: null, hp: 980, damage: 30, acts: [3] },
  ],
};

export const BASE_UNLOCKS = {
  starting: {
    spires: ["addition"],
    relics: ["quick-slate", "iron-theorem", "vital-reserve", "merchant-ledger"],
    events: ["whispering-slate", "blood-merchant", "camp-of-echoes", "oracle-flame", "omens-hand"],
    monsters: ["fiend", "fang"],
    elites: ["guard"],
    bosses: ["sentinel"],
  },
  portalArray: [
    {
      tier: 1,
      cost: { emberwood: 2 },
      title: "Ashen Gate",
      description: "A second gate answers the array and the hollow stirs awake.",
      unlocks: {
        spires: ["subtraction"],
      },
    },
    {
      tier: 2,
      cost: { emberwood: 2, thorium: 1 },
      title: "Echo Forge",
      description: "A deeper current is bound into steel and a new road answers.",
      unlocks: {
        spires: ["multiplication"],
      },
    },
    {
      tier: 3,
      cost: { emberwood: 1, thorium: 2 },
      title: "Sanctum Rift",
      description: "The fractured way is cut open and the sanctum can be reached.",
      unlocks: {
        spires: ["division"],
      },
    },
    {
      tier: 4,
      cost: { thorium: 2, eternium: 1 },
      title: "Crown Nexus",
      description: "The roads converge and the crowned ascent reveals itself.",
      unlocks: {
        spires: ["mixed"],
      },
    },
  ],
  archive: [
    {
      tier: 1,
      cost: { emberwood: 2 },
      title: "Hard-Choice Records",
      description: "Older records are unsealed, and stranger bargains begin to answer the climb.",
      unlocks: {
        events: ["shattered-dynamo", "mirror-of-edges", "sealed-vault"],
      },
    },
    {
      tier: 2,
      cost: { thorium: 2, eternium: 1 },
      title: "Forbidden Routes",
      description: "The black ledgers are opened, drawing in rarer vows and riskier pacts.",
      unlocks: {
        events: ["oath-pyre", "ghost-market"],
      },
    },
  ],
  relicForge: [
    {
      tier: 1,
      cost: { emberwood: 1, thorium: 1 },
      title: "Field Relics",
      description: "The forge begins turning out steadier charms and battle trinkets.",
      unlocks: {
        relics: ["scholar-spark", "emerald-script", "rogue-loop", "guardian-circuit", "combo-censer"],
      },
    },
    {
      tier: 2,
      cost: { thorium: 2, eternium: 1 },
      title: "Mythic Engine",
      description: "The deeper furnaces ignite, drawing forth rarer instruments of power.",
      unlocks: {
        relics: ["assassin-abacus", "arcane-engine", "focus-prism", "stability-glyph", "battery-core", "tempo-sigil", "war-drum"],
      },
    },
  ],
  warRoom: [
    {
      tier: 1,
      cost: { emberwood: 1, thorium: 1 },
      title: "Expanded Patrols",
      description: "Wider patrol paths rouse fresh fiends and harder wardens.",
      unlocks: {
        monsters: ["shade", "brute", "crow"],
        elites: ["warden", "disciple"],
      },
    },
    {
      tier: 2,
      cost: { thorium: 2, eternium: 1 },
      title: "Boss Hunt Orders",
      description: "Ancient hunt marks are restored, and stronger champions answer each act.",
      unlocks: {
        monsters: ["priest"],
        elites: ["breaker"],
        bosses: ["gatekeeper", "sigil-engine", "obelisk-heart"],
      },
    },
  ],
};

export const BASE_BUILDING_ORDER = ["portalArray", "archive", "relicForge", "warRoom"];

export const BASE_BUILDING_LABELS = {
  portalArray: {
    name: "Portal Array",
    short: "Spires",
    description: "Rekindles the dead gates that lead deeper into the frontier.",
  },
  archive: {
    name: "Archive",
    short: "Events",
    description: "Unseals old records, omens, and stranger chambers.",
  },
  relicForge: {
    name: "Relic Forge",
    short: "Relics",
    description: "Coaxes rarer relics and battle charms into the climb.",
  },
  warRoom: {
    name: "War Room",
    short: "Enemies",
    description: "Stirs fiercer denizens, wardens, and throne-beasts.",
  },
};

export const SHOP_TEMPLATE = [
  { id: "upgrade-atk", kind: "ACTION_UPGRADE", actionId: "atk", label: "Sharpen Strike", baseCost: 110 },
  { id: "upgrade-blk", kind: "ACTION_UPGRADE", actionId: "blk", label: "Temper Guard", baseCost: 110 },
  { id: "upgrade-aoe", kind: "ACTION_UPGRADE", actionId: "aoe", label: "Prime Sunder Wave", baseCost: 135 },
  { id: "herb-cache", kind: "HERBS", herbs: { white: 1, yellow: 1, blue: 1 }, label: "Apothecary Cache", baseCost: 120 },
  { id: "stat-focus", kind: "STAT", stat: "focus", label: "Clarity Draught", baseCost: 90 },
  { id: "stat-str", kind: "STAT", stat: "str", label: "Iron Draft", baseCost: 90 },
  { id: "remove-weakness", kind: "REMOVE", label: "Purge Doubt", baseCost: 150 },
];

export const EVENT_TEMPLATES = [
  {
    id: "whispering-slate",
    title: "Whispering Slate",
    text: "A slate of living sigils offers a blunt lesson: power comes faster to those who commit.",
    choices: [
      {
        id: "focus-study",
        label: "Study The Glyphs",
        description: "Gain +2 Focus and steady your critical rhythm.",
        effect: { stats: { focus: 2 } },
      },
      {
        id: "temper-hard",
        label: "Hone A Hard Lesson",
        description: "Upgrade your lowest-level HARD action.",
        effect: { upgradeLowestHard: 1 },
      },
      {
        id: "leave",
        label: "Move On",
        description: "Leave the lesson behind and keep climbing.",
        effect: {},
      },
    ],
  },
  {
    id: "blood-merchant",
    title: "Blood Merchant",
    text: "A masked trader offers momentum at a price only a desperate climber would welcome.",
    choices: [
      {
        id: "pay-blood",
        label: "Trade Blood For Relic",
        description: "Lose 12% max HP and claim a random relic.",
        effect: { loseHpPct: 0.12, randomRelic: true },
      },
      {
        id: "take-gold",
        label: "Take The Payout",
        description: "Take the coin and walk away clean.",
        effect: { gold: 140 },
      },
      {
        id: "refuse",
        label: "Refuse",
        description: "Leave the bargain behind.",
        effect: {},
      },
    ],
  },
  {
    id: "camp-of-echoes",
    title: "Camp Of Echoes",
    text: "You find a training ring where every solved pattern leaves a mark on the body.",
    choices: [
      {
        id: "strength-drill",
        label: "Hammer Drill",
        description: "Gain +2 STR and +10 max HP.",
        effect: { stats: { str: 2 }, maxHp: 10 },
      },
      {
        id: "recover",
        label: "Recover And Refocus",
        description: "Gain one White Herb, one Yellow Herb, and +1 Focus.",
        effect: { herbs: { white: 1, yellow: 1 }, stats: { focus: 1 } },
      },
      {
        id: "double-temper",
        label: "Repeat The Forms",
        description: "Upgrade two random actions.",
        effect: { upgradeRandomActions: 2 },
      },
    ],
  },
  {
    id: "oracle-flame",
    title: "Oracle Flame",
    text: "A prophetic flame shows the next stretch of the climb and asks what kind of legend you mean to become.",
    choices: [
      {
        id: "balanced-growth",
        label: "Take The Whole Measure",
        description: "Gain +1 STR, +1 VIT, and +1 FOCUS.",
        effect: { stats: { str: 1, vit: 1, focus: 1 } },
      },
      {
        id: "elite-hunter",
        label: "Hunt The Peak",
        description: "Gain a relic and 60 gold.",
        effect: { randomRelic: true, gold: 60 },
      },
      {
        id: "quiet-step",
        label: "Hold A Quiet Step",
        description: "Gain one White Herb and one Blue Herb, then keep the run stable.",
        effect: { herbs: { white: 1, blue: 1 } },
      },
    ],
  },
  {
    id: "omens-hand",
    title: "Hand Of Omens",
    text: "A hooded broker lays down three carved tokens and offers a best-of-three wager: stone, scroll, and shears.",
    choices: [
      {
        id: "take-the-wager",
        label: "Take The Wager",
        description: "Play best of three. Win a relic. Lose blood.",
        effect: {
          minigameId: "omens-hand",
          onWin: { randomRelic: true, gold: 40 },
          onLose: { loseHpPct: 0.08 },
          onDraw: { gold: 60 },
        },
      },
      {
        id: "keep-walking",
        label: "Keep Walking",
        description: "Leave the broker and keep the climb steady.",
        effect: {},
      },
    ],
  },
  {
    id: "shattered-dynamo",
    title: "Shattered Dynamo",
    text: "A cracked engine still beats under the stone. You can bind its rhythm, but the machine asks for payment first.",
    choices: [
      {
        id: "bind-core",
        label: "Bind The Core",
        description: "Lose 18% max HP. Gain Battery Core for +1 energy every turn.",
        effect: { loseHpPct: 0.18, relicId: "battery-core" },
      },
      {
        id: "carve-tempo",
        label: "Carve The Tempo Sigil",
        description: "Pay 90 gold. Gain Tempo Sigil so your first action each turn costs 1 less.",
        effect: { loseGold: 90, relicId: "tempo-sigil" },
      },
      {
        id: "rupture-shell",
        label: "Rupture The Shell",
        description: "Gain 170 gold, but lose 10% max HP in the blast.",
        effect: { gold: 170, loseHpPct: 0.1 },
      },
    ],
  },
  {
    id: "mirror-of-edges",
    title: "Mirror Of Edges",
    text: "A spectral reflection offers perfect form. It will hone one edge of your kit, but only if you accept the cut that comes with it.",
    choices: [
      {
        id: "cut-for-strike",
        label: "Bleed For Precision",
        description: "Lose 14% max HP. Upgrade Strike by 2 levels.",
        effect: { loseHpPct: 0.14, upgradeActionId: "atk", upgradeActionLevels: 2 },
      },
      {
        id: "gold-for-blast",
      label: "Feed The Sunder Wave",
      description: "Pay 80 gold. Upgrade Sunder Wave by 1 level and gain +1 Focus.",
        effect: { loseGold: 80, upgradeActionId: "aoe", upgradeActionLevels: 1, stats: { focus: 1 } },
      },
      {
        id: "look-away",
        label: "Look Away",
        description: "Leave the mirror untouched.",
        effect: {},
      },
    ],
  },
  {
    id: "sealed-vault",
    title: "Sealed Vault",
    text: "A pressure door grinds open just enough to tempt you. The Obelisk makes it clear: every prize here costs blood or coin.",
    choices: [
      {
        id: "break-lock",
        label: "Break The Lock",
        description: "Lose 22% max HP and seize a random relic.",
        effect: { loseHpPct: 0.22, randomRelic: true },
      },
      {
        id: "pay-mechanism",
        label: "Prime The Mechanism",
        description: "Pay 120 gold. Gain Stability Glyph and upgrade Guard by 1 level.",
        effect: { loseGold: 120, relicId: "stability-glyph", upgradeActionId: "blk", upgradeActionLevels: 1 },
      },
      {
        id: "take-the-coin",
        label: "Take The Coin",
        description: "Gain 220 gold, but lose 8% max HP escaping the trap.",
        effect: { gold: 220, loseHpPct: 0.08 },
      },
    ],
  },
  {
    id: "oath-pyre",
    title: "Oath Pyre",
    text: "An ancient pyre burns with promises. You may swear yourself to force, precision, or endurance, but every vow demands a visible sacrifice.",
    choices: [
      {
        id: "vow-force",
        label: "Swear Force",
        description: "Lose 15% max HP. Gain +3 STR.",
        effect: { loseHpPct: 0.15, stats: { str: 3 } },
      },
      {
        id: "vow-precision",
        label: "Swear Precision",
        description: "Lose 15% max HP. Gain +3 Focus.",
        effect: { loseHpPct: 0.15, stats: { focus: 3 } },
      },
      {
        id: "vow-endurance",
        label: "Swear Endurance",
        description: "Pay 110 gold. Gain +2 VIT and an apothecary bundle.",
        effect: { loseGold: 110, stats: { vit: 2 }, herbs: { white: 1, yellow: 1 } },
      },
    ],
  },
  {
    id: "ghost-market",
    title: "Ghost Market",
    text: "A silent bazaar appears between floors. Its wares are exceptional, but the merchants never accept a simple price.",
    choices: [
      {
        id: "buy-prism",
        label: "Buy The Prism",
        description: "Pay 130 gold. Gain Focus Prism.",
        effect: { loseGold: 130, relicId: "focus-prism" },
      },
      {
        id: "steal-ledger",
        label: "Steal The Ledger",
        description: "Lose 20% max HP. Gain Merchant Ledger and 80 gold.",
        effect: { loseHpPct: 0.2, relicId: "merchant-ledger", gold: 80 },
      },
      {
        id: "sell-a-memory",
        label: "Sell A Memory",
        description: "Upgrade your lowest HARD action, then lose 10% max HP.",
        effect: { upgradeLowestHard: 1, loseHpPct: 0.1 },
      },
    ],
  },
];

export const TRAINING_REWARDS = [
  {
    id: "talent-spark",
    kind: "SKILL_POINT",
    amount: 1,
    label: "Talent Ember",
    description: "Bank 1 skill point for your class tree.",
  },
  {
    id: "camp-drill",
    kind: "SKILL_POINT",
    amount: 1,
    label: "War Doctrine",
    description: "Gain 1 skill point and refine your discipline at the next opening.",
  },
  {
    id: "strike-drill",
    kind: "ACTION",
    actionId: "atk",
    label: "Sharpen Strike",
    description: "Upgrade Strike by 1 level.",
  },
  {
    id: "guard-drill",
    kind: "ACTION",
    actionId: "blk",
    label: "Temper Guard",
    description: "Upgrade Guard by 1 level.",
  },
  {
    id: "blast-drill",
    kind: "ACTION",
    actionId: "aoe",
    label: "Prime Sunder Wave",
    description: "Upgrade Sunder Wave by 1 level.",
  },
  {
    id: "herb-bundle",
    kind: "HERBS",
    herbs: { white: 1, blue: 1 },
    label: "Apothecary Bundle",
    description: "Gain one White Herb and one Blue Herb.",
  },
  {
    id: "focus-drill",
    kind: "STAT",
    stat: "focus",
    amount: 2,
    label: "Keen Study",
    description: "Gain +2 Focus.",
  },
  {
    id: "strength-drill",
    kind: "STAT",
    stat: "str",
    amount: 2,
    label: "Iron Lesson",
    description: "Gain +2 STR.",
  },
  {
    id: "vital-drill",
    kind: "STAT",
    stat: "vit",
    amount: 1,
    label: "Stoneblood Drill",
    description: "Gain +1 VIT and +10 max HP.",
  },
  {
    id: "field-rations",
    kind: "HERBS",
    herbs: { yellow: 1, red: 1 },
    label: "Field Satchel",
    description: "Gain one Yellow Herb and one Red Herb.",
  },
  {
    id: "gold-cache",
    kind: "GOLD",
    amount: 90,
    label: "Smuggled Cache",
    description: "Gain 90 extra gold.",
  },
];

export const MINIGAME_TEMPLATES = {
  "omens-hand": {
    id: "omens-hand",
    title: "Hand Of Omens",
    subtitle: "Best of three. Stone breaks Shears, Shears cut Scroll, Scroll binds Stone.",
    type: "RPS",
    targetWins: 2,
    moves: [
      { id: "stone", label: "Stone", beats: "shears" },
      { id: "scroll", label: "Scroll", beats: "stone" },
      { id: "shears", label: "Shears", beats: "scroll" },
    ],
  },
};

export const SCREEN = {
  HUB: "HUB",
  MAP: "MAP",
  BATTLE: "BATTLE",
  EVENT: "EVENT",
  MINIGAME: "MINIGAME",
  TREASURE: "TREASURE",
  SHOP: "SHOP",
  REST: "REST",
  VICTORY: "VICTORY",
  RUN_REPORT: "RUN_REPORT",
  GAMEOVER: "GAMEOVER",
};
